### ISSUE TITLE
Allow performance section to be left unset.

### ISSUE THREAD

**Issue by vesterlay** [benjamimgois/goverlay#10]
If I'm not mistaken, every option set in performance section takes the priority over the game. Please add the functionality to leave it unset.

**Comment by benjamimgois** [comment]
Sure, i'll add it to my to-do list

**Comment by benjamimgois** [comment]
@vesterlay i was checking better your request and i really don't see the need for a unset option. If you don't want to force a FPS limit just choose "unlimited". If you don't want to force vsync, just choose "off". Am i missing anything ?

**Comment by vesterlay** [comment]
When the FPS limit is set to unlimited, it doesn't let the game decide, but forces fps to be unlimited. The same applies to vsync, I just want to be an option to let the game launch with it's own configuration.

**Comment by benjamimgois** [comment]
@vesterlay  Could you try this test build ? i just add an option "unset" to FPS and VSYNC. See if it solves the problem for you

[goverlay.tar.gz](https://github.com/benjamimgois/goverlay/files/4398159/goverlay.tar.gz)

**Comment by vesterlay** [comment]
Works like a charm, thanks for the help.

**Comment by benjamimgois** [comment]
Nice ! thanks for the feedback.
