### ISSUE TITLE
Options blacked out.

### ISSUE THREAD

**Issue by Momotin** [benjamimgois/goverlay#10]
![image](https://user-images.githubusercontent.com/80270576/182385630-1d3ddc56-2f76-492a-8684-2863baea4675.png)

As you can see from the screenshot. the options are blacked out. i can hover over them and see the little window that explains what it does.
Using Plasma 5.25.3 with Wayland.

**Comment by benjamimgois** [comment]
@Momotin this is probably a plasma theme incompatibility. The supported themes are Breeze and Adwaita. You can force goverlay to run with a specific theme to fix the issue. You can try one of the following options in a terminal. See if it wors.

`goverlay --style breeze`
`goverlay --style fusion`
`goverlay --style windows`

**Comment by Momotin** [comment]
Thank you. works now.

**Comment by davigamer987** [comment]
none of those options worked for me, using latest kde with layan theme
