### ISSUE TITLE
Config directory? How can I modify the listed fps limit?

### ISSUE THREAD

**Issue by spartan195** [benjamimgois/goverlay#100]
Hello, 
I can't find where the config is stored, or how to modify by hand the preset fps limits.
My screen is 144hz but I cannot select 72fps as limit, how could I modify this? I would like to change it into the mangohud file but I cannot see where it is stored.

Thanks!

**Comment by spartan195** [comment]
Ok the mangohud file is in:
`/home/$USER/.config/MangoHud/MangoHud.conf`

And I can successfully add a 72fps lock in the list but everytime I modify something from the gooverlay It's overritten.

Could we get an option to add a custom fps cap? I can see it's as easy as adding an input field.

Thanks!

**Comment by benjamimgois** [comment]
Sure, I'll work in a custom field for a future update.

**Comment by benjamimgois** [comment]
New field for a negative offset implemented in 1.2
