### ISSUE TITLE
Compiled goverlay crashes with ExceptionOccurred

### ISSUE THREAD

**Issue by DarkSwan86** [benjamimgois/goverlay#101]
Hi!

I'm trying to use GOverlay with OpenGL games (my card doesn't support vulkan) but when i try to use the compiled version from Pamac (i'm using Manjaro KDE), with mangohud also instralled. When started, it crashes with this error:

[FORMS.PP] ExceptionOccurred 
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $0000000000584BD3
  $0000000000563A29
  $00000000006EE238
  $00000000006EDBCA
  $00000000006E97DC
  $00000000005F1C19
  $00000000005F1B1B
  $000000000044B52A
  $000000000044A3A3
  $000000000043A1EC
[FORMS.PP] ExceptionOccurred 

System information:

System:    Host: leonardo-pc Kernel: 5.4.80-2-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.20.4 Distro: Manjaro Linux 

CPU:       Info: Dual Core Intel Core i3-2350M [MT MCP] speed: 798 MHz min/max: 800/2300 MHz 

Graphics:  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics driver: i915 v: kernel 
                  Device-2: NVIDIA GF119M [GeForce 610M] driver: nouveau v: kernel 
                  Device-3: Sunplus Innovation Asus Webcam type: USB driver: uvcvideo 

Display: wayland server: X.Org 1.20.10 driver: intel,nouveau unloaded: modesetting resolution: 1366x768~60Hz 

OpenGL: renderer: Mesa DRI Intel HD Graphics 3000 (SNB GT2) v: 3.3 Mesa 20.2.3 

If you need more information just ask! Thanks!

**Comment by benjamimgois** [comment]
Hi @DarkSwan86 , it seems a problem with you lazarus installation. First remove your current lazarus build with pamac, Then just try o install `goverlay-git` from the AUR. It should ask you for required dependencies. 

Important to note that you don't need to build goverlay, if you just want to use it install only the binary version `goverlay-bin` also avaiable on the AUR.

`sudo pamac install goverlay-bin`

**Comment by DarkSwan86** [comment]
Hi @benjamimgois ! I've removed lazarus with pamac and tried to search goverlay-bin on AUR but still ask to be build. 

There is no binary on AUR :( (i've used your command also). 

goverlay-bin ask only for qt5pas 2.6.r63484-2. 

I have to try the git version but ask to download all the lazarus package that is 202 Mb. Is it required right?

Thanks for all the support!

**Comment by yochananmarqos** [comment]
@DarkSwan86 All AUR packages need to be built no matter the source. `goverlay-bin` is indeed the binary package. `qt5pas` is required either way.

@benjamimgois Tip: It's not necessary to use `sudo` with Pamac, it will prompt for authentication when needed.

**Comment by nutta-git** [comment]
I am also facing this issue with fedora 33 

```
QSocketNotifier: Can only be used with threads started with QThread
[FORMS.PP] ExceptionOccurred 
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $0000000000581253
  $00000000005600A9
  $00000000006E52ED
  $00000000006E4CCD
  $00000000006E0E03
  $00000000005EE061
  $00000000005EDF7B
  $000000000044B46A
  $000000000044A2E0
[FORMS.PP] ExceptionOccurred 
```

**Comment by benjamimgois** [comment]
@yochananmarqos i didn't know that. I'll update the documentation. 

@nutta-git i don't know why this error is happening... i have no problems on manjaro, i'll investigate. Right now i would suggest to get the binary version and remember that `qt5pas` is required to run the application.

**Comment by MichaelLawton** [comment]
I also have the same output as @nutta-git when using the Fedora 33 repo package. When running the binary in the tarball I get a slightly more detailed stack trace:

```
QSocketNotifier: Can only be used with threads started with QThread
[FORMS.PP] ExceptionOccurred 
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $0000000000584BD3  GETSYSCOLOR,  line 485 of include/winapi.inc
  $0000000000563A29  COLORTORGB,  line 2531 of graphics.pp
  $00000000006EE238  CREATEOBJECTS,  line 2363 of qtobjects.pas
  $00000000006EDBCA  CREATE,  line 2271 of qtobjects.pas
  $00000000006E97DC  QTDEFAULTCONTEXT,  line 919 of qtobjects.pas
  $00000000005F1C19  DESTROY,  line 93 of qtobject.inc
  $00000000005F1B1B  CREATE,  line 70 of qtobject.inc
  $000000000044B52A  CREATEWIDGETSET,  line 2223 of forms.pp
  $000000000044A3A3  INTERFACES_$$_init$,  line 36 of interfaces.pp
  $000000000043A1EC
[FORMS.PP] ExceptionOccurred
```

**Comment by getchoo** [comment]
Bumping this as I got the same issue, but while using the Fedora 34 repo package.
```
QSocketNotifier: Can only be used with threads started with QThread
[FORMS.PP] ExceptionOccurred 
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $0000000000586663
  $00000000005654B9
  $00000000006EA96D
  $00000000006EA34D
  $00000000006E6483
  $00000000005F3471
  $00000000005F338B
  $000000000044B46A
  $000000000044A2E0
[FORMS.PP] ExceptionOccurred
```
@MichaelLawton's X compatibility mode idea is still working, albeit with the occasional write access issue I get with a warning about failing to write to my home directory (I haven't been able to reproduce it after manually editing `MangoHud.conf` though).

**Comment by benjamimgois** [comment]
Guys, this issue was openned several times. It's all related to wayland support, and for that we depend entirely on lazarus implement it. I'm closing it for now.
