### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Darkwing975** [benjamimgois/goverlay#105]
I can't build goverlay as it gives me this error: 
`(9022) Compiling resource /home/therick/goverlay/lib/x86_64-linux/goverlay.or
(9015) Linking /home/therick/goverlay/goverlay
/usr/bin/ld.bfd: cannot find -lQt5Pas
/home/therick/goverlay/goverlay.lpr(26,1) Error: (9013) Error while linking
/home/therick/goverlay/goverlay.lpr(26,1) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
Error: (lazarus) Compile Project, Mode: Release, Target: goverlay: stopped with exit code 1
Error: (lazbuild) failed compiling of project /home/therick/goverlay/goverlay.lpi
make: *** [Makefile:8: goverlay] Error 2`

**Comment by Darkwing975** [comment]
I have installed Lazarus and I have mangohud installed

**Comment by benjamimgois** [comment]
@Darkwing975 i had uploaded a early git code that might have issues. I'll release the 0.4.4 version soon. In the mean time i would suggest to use the stable or the precompiled build.

**Comment by Darkwing975** [comment]
Yes I've got it like that now.

**Comment by benjamimgois** [comment]
Is it solved with the latest update ?

**Comment by Darkwing975** [comment]
Not sure, I've switched back to windows so I'm not sure if I'll be able to test it.

**Comment by benjamimgois** [comment]
Ok, let me know if you try it again. Thanks for the feedback.
