### ISSUE TITLE
Release not updated

### ISSUE THREAD

**Issue by Xdavius** [benjamimgois/goverlay#106]
Hi,

Since Antiz PR for QT6, release is not updated, but tag is.

Please, update the tar.xz 

Needed for packaging.

Thank you 

xdavius

**Comment by benjamimgois** [comment]
Just update the file @Xdavius , thanks for the tip.

**Comment by Xdavius** [comment]
> Just update the file @Xdavius , thanks for the tip.

Thanks a lot. still testing the build from source and make it working an all debian based, with the lazarus dependency hell.

Just, I've got this result after building on debian stable. Do you know why ? so I can improve.

Thank you


![Screenshot_20240401_134319](https://github.com/benjamimgois/goverlay/assets/66792063/83977701-82dd-4a86-bc41-520e2044ecac)

**Comment by Xdavius** [comment]
sorry, duplicate : https://github.com/benjamimgois/goverlay/issues/84

closing and go to issue 84
