### ISSUE TITLE
Cannot run in Wayland

### ISSUE THREAD

**Issue by KayKay91** [benjamimgois/goverlay#107]
When trying to run GOverlay in a Wayland session, this error pops up in terminal:

> [FORMS.PP] ExceptionOccurred 
>   Sender=EAccessViolation
>   Exception=Access violation
>   Stack trace:
>   $00000000004E8F03
>   $00000000004CE749
>   $00000000005DA6E8
>   $00000000005DA07A
>   $00000000005D633C
>   $000000000052A179
>   $000000000052A07B
>   $000000000042DB9A
>   $000000000042CFC3
 > [FORMS.PP] ExceptionOccurred

**Comment by benjamimgois** [comment]
@KayKay91 to run it on Wayland, you need to force the x11 backend. Try to run it with:

`QT_QPA_PLATFORM=xcb goverlay --style fusion`


Some distributions (like manjaro) do it automagically for you.
![image](https://user-images.githubusercontent.com/7688496/107027987-aa49a400-678b-11eb-9930-2879701310a5.png)

**Comment by benjamimgois** [comment]
@KayKay91 does it work for you now ?

**Comment by benjamimgois** [comment]
I'll assume it woked.

**Comment by KyleUltimate** [comment]
can confirm this works
