### ISSUE TITLE
Erro trying to run on Fedora 40

### ISSUE THREAD

**Issue by IagoJevaux** [benjamimgois/goverlay#108]
After installation using 'dnf install goverlay', it doesn't work

When running on terminal the following error is presented:
/usr/libexec/goverlay: symbol lookup error: /lib64/libQt6Pas.so.6: undefined symbol: _ZNK7QString12isSimpleTextEv, version Qt_6

DIdn't try to build from source due Lazarus Dependecy hell.

- Memory                                    16,0 GiB
- Processor                                 11th Gen Intel® Core™ i5-11400H × 12
- Graphics                                   Intel® UHD Graphics (TGL GT1)
- Graphics 1                                NVIDIA GeForce RTX™ 3050 Laptop GPU
- Disk capacity                            512,1 GB

Software info
- Firmware version                         V1.20
- OS name                                     Fedora Linux 40 (Workstation Edition)
- OS Version                                  (null)
- OS archtecture                                64 bits
- Gnome Version                           46
- Display Manager                        Wayland
- Kernel version                            Linux 6.8.7-300.fc40.x86_64

**Comment by AndreCox** [comment]
Exact same issue on Fedora 40, since it's giving us a Qt6 error we should probably be looking into changes to Qt made between fedora 39 and 40 in qt.

**Comment by Linkalinux** [comment]
Good afternoon, I have the same problem Gnome 46 Fedora 40
![Снимок экрана от 2024-04-28 12-12-03](https://github.com/benjamimgois/goverlay/assets/127676248/5da6eff6-a584-49dd-9389-f73ff9252e15)

**Comment by IagoJevaux** [comment]
> Exact same issue on Fedora 40, since it's giving us a Qt6 error we should probably be looking into changes to Qt made between fedora 39 and 40 in qt.

I don't think it's a QT6 error by itself. The issue points to /lib64/libQt6Pas.so.6, which is a Lazarus library.
If someone has a working Lazarus in Fedora 40 maybe trying to compile from source might give a bit more information.

**Comment by Ironfist69** [comment]
same issue, I'm also using Fedora 40

**Comment by mort-underscore** [comment]
Same issue running fedora kde 40.

**Comment by aj53108** [comment]
Can confirm, same issue on Fedora 40 KDE.

**Comment by AndreCox** [comment]
> > Exact same issue on Fedora 40, since it's giving us a Qt6 error we should probably be looking into changes to Qt made between fedora 39 and 40 in qt.
> 
> I don't think it's a QT6 error by itself. The issue points to /lib64/libQt6Pas.so.6, which is a Lazarus library. If someone has a working Lazarus in Fedora 40 maybe trying to compile from source might give a bit more information.

I can give it a try to compile from source

**Comment by AndreCox** [comment]
Well didn't get very far with building it from source, here's the error message.

```
lazbuild -B goverlay.lpi --bm=Release 
CopySecondaryConfigFile /etc/lazarus/environmentoptions.xml -> /home/andre/.lazarus/environmentoptions.xml
Info: (lazarus) [CompilePackage]: CheckIfPackageNeedsCompilation returned mrNo for package FCL 1.0.1
Info: (lazarus) [CompilePackage]: CheckIfPackageNeedsCompilation returned mrNo for package LazUtils 1.0
Info: (lazarus) [CompilePackage]: CheckIfPackageNeedsCompilation returned mrNo for package freetypelaz 1.0
Info: (lazarus) [CompilePackage]: CheckIfPackageNeedsCompilation returned mrNo for package LCLBase 3.2
Hint: (lazarus) Missing state file of LCL 3.2: /usr/lib64/lazarus/lcl/units/x86_64-linux/qt6/lcl.compiled
Hint: (lazarus) normal output directory of package LCL 3.2 is not writable: "/usr/lib64/lazarus/lcl/units/x86_64-linux/qt6/"
TParsedCompilerOptions.SetOutputDirectoryOverride New=/home/andre/.lazarus/lib/units/x86_64-linux/qt6
Hint: (lazarus) Missing state file of LCL 3.2: /home/andre/.lazarus/lib/units/x86_64-linux/qt6/lcl.compiled
Hint: (lazarus) Missing state file of LazOpenGLContext 0.0.1: /usr/lib64/lazarus/components/opengl/lib/x86_64-linux/qt6/lazopenglcontext.compiled
Hint: (lazarus) normal output directory of package LazOpenGLContext 0.0.1 is not writable: "/usr/lib64/lazarus/components/opengl/lib/x86_64-linux/qt6/"
TParsedCompilerOptions.SetOutputDirectoryOverride New=/home/andre/.lazarus/lib/LazOpenGLContext/lib/x86_64-linux/qt6
Hint: (lazarus) Missing state file of LazOpenGLContext 0.0.1: /home/andre/.lazarus/lib/LazOpenGLContext/lib/x86_64-linux/qt6/lazopenglcontext.compiled
Hint: (11030) Start of reading config file /etc/fpc.cfg
Hint: (11031) End of reading config file /etc/fpc.cfg
Free Pascal Compiler version 3.2.2 [2024/01/24] for x86_64
Copyright (c) 1993-2021 by Florian Klaempfl and others
(1002) Target OS: Linux for x86-64
(3104) Compiling lcl.pas
/usr/lib64/lazarus/lcl/interfaces/lcl.pas(11,3) Fatal: (10022) Can't find unit AllLCLIntfUnits used by LCL
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
Error: (lazarus) Compile package LCL 3.2: stopped with exit code 1
Error: (lazarus) [TLazPackageGraph.CompileRequiredPackages] "Exit code 1"
Error: (lazbuild) Project dependencies of /tmp/goverlay/goverlay.lpi
```

Also not imposible that I messed something up with dependencies but maybe someone better at figuring out error codes may find this useful.

**Comment by AndreCox** [comment]
Also managed to track down this issue on the latest version of lazarus

 ` - nothing provides fpc = 3.2.2-1 needed by lazarus-3.2-0.x86_64 from @commandline`

**Comment by benjamimgois** [comment]
Hey guys, i didn't test on Fedora but i think the repo that provides the ubuntu libqt6pas also provides a rpm package. Check if it works

https://github.com/davidbannon/libqt6pas

**Comment by Plyply99** [comment]
The updated files are in the Fedora Rawhide repo.
I uninstalled goverlay then installed from rawhide and it works fine.

**Comment by IagoJevaux** [comment]
> The updated files are in the Fedora Rawhide repo. I uninstalled goverlay then installed from rawhide and it works fine.

Didn't work for me. Downloaded version goverlay-1.1.1-2.fc40.x86_64 from rawhide and same error.
Can you provide a link and installation method used?

**Comment by Plyply99** [comment]
> > The updated files are in the Fedora Rawhide repo. I uninstalled goverlay then installed from rawhide and it works fine.
> 
> Didn't work for me. Downloaded version goverlay-1.1.1-2.fc40.x86_64 from rawhide and same error. Can you provide a link and installation method used?

I think it was:
sudo dnf remove goverlay
sudo dnf remove libqt6pas6 libqt6pas6-devel
sudo dnf --enablerepo=rawhide install goverlay

The devel package might not be installed, if so just ignore it.

**Comment by IagoJevaux** [comment]
> > > The updated files are in the Fedora Rawhide repo. I uninstalled goverlay then installed from rawhide and it works fine.
> > 
> > 
> > Didn't work for me. Downloaded version goverlay-1.1.1-2.fc40.x86_64 from rawhide and same error. Can you provide a link and installation method used?
> 
> I think it was: sudo dnf remove goverlay sudo dnf remove libqt6pas6 libqt6pas6-devel sudo dnf --enablerepo=rawhide install goverlay
> 
> The devel package might not be installed, if so just ignore it.

Are you sure you did this in a clean fedora 40? 
libqt6pas6 libqt6pas6-devel are not installed and I can't install them on F40 because the only available source (https://github.com/davidbannon/libqt6pas) is based on qt6 6.2 and F40 ships with qt6 6.7...
Also, "sudo dnf --enablerepo=rawhide install goverlay" returns with "unkown repo: rawhide".

**Comment by Plyply99** [comment]
You have to add the repo.
sudo dnf install fedora-repos-rawhide

**Comment by IagoJevaux** [comment]
> You have to add the repo. sudo dnf install fedora-repos-rawhide

Is it safe to add rawhide repo? I had a bad experience in the past when I enabled rawhide systemwide. Since then I didn't try to enable it ever again (thought that they might have added a way to fetch packages from rawhide without having to enable the repo - silly me).

**Comment by Plyply99** [comment]
> > You have to add the repo. sudo dnf install fedora-repos-rawhide
> 
> Is it safe to add rawhide repo? I had a bad experience in the past when I enabled rawhide systemwide. Since then I didn't try to enable it ever again (thought that they might have added a way to fetch packages from rawhide without having to enable the repo - silly me).
You are just adding the repo and installing a few packages from it. It's fine. It will only install goverlay and required dependecies.

sudo dnf install fedora-repos-rawhide
sudo dnf --enablerepo=rawhide install goverlay

**Comment by IagoJevaux** [comment]
> > > You have to add the repo. sudo dnf install fedora-repos-rawhide
> > 
> > 
> > Is it safe to add rawhide repo? I had a bad experience in the past when I enabled rawhide systemwide. Since then I didn't try to enable it ever again (thought that they might have added a way to fetch packages from rawhide without having to enable the repo - silly me).
> > You are just adding the repo and installing a few packages from it. It's fine. It will only install goverlay and required dependecies.
> 
> sudo dnf install fedora-repos-rawhide sudo dnf --enablerepo=rawhide install goverlay

Didn't work, same error when installing from rawhide...

**Comment by YanEx13** [comment]
The goverlay-1.1.1-2.fc40.src.rpm update has arrived on Fedora 40, everything works, thank you!

**Comment by IagoJevaux** [comment]
> The goverlay-1.1.1-2.fc40.src.rpm update has arrived on Fedora 40, everything works, thank you!

Actually Lazarus updated with a fix to QT6Pas. It's working now.

Issue closed.
