### ISSUE TITLE
i cant disable "Global Enable"

### ISSUE THREAD

**Issue by kleinermob** [benjamimgois/goverlay#108]

**Comment by Rajalolxd** [comment]
removed line from .profiles, works   now

**Comment by benjamimgois** [comment]
The global enable for mangohud isn't working the way it should for some users. I'll try to reimplement it with a new logic in a future release.

**Comment by kajlando** [comment]
All commads are in: /usr/share/doc/mangohud/MangoHud.conf.example
After adding:
### Disable / hide the hud by deafult
no_display
in: ~/.config/MangoHud/MangoHud.conf
it finally turned off.
Goverlay path is in: ~/.config/goverlay/MangoHud.conf
Interestingly you DON'T have to reboot (like with Goverlay) by doing that.
Mangohud instantly know that you turned off it globally.

**Comment by kajlando** [comment]
All commads are in: /usr/share/doc/mangohud/MangoHud.conf.example
After adding:
.### Disable / hide the hud by deafult
no_display
in: ~/.config/MangoHud/MangoHud.conf
it finally turned off.
Goverlay path is in: ~/.config/goverlay/MangoHud.conf
Interestingly you DON'T have to reboot (like with Goverlay) by doing that.
Mangohud instantly know that you turned it off globally!
So Global Enable switch is kinda useless right now (at least for me).

**Comment by Tokariew** [comment]
where is this .profiles file?

**Comment by NaturalHate** [comment]
Is there a workaround when it doesn't work the opposite way? I want to enable the hud globally, but despite being toggled it is not showing up unless I use the prefix, and then the hotkey to toggle it is still not working either. I did toggle it back and forth without restarting when I played around after the first installation, so I don't know if that broke it / put it out of sync somehow.

**Comment by kajlando** [comment]
> Is there a workaround when it doesn't work the opposite way? I want to enable the hud globally, but despite being toggled it is not showing up unless I use the prefix, and then the hotkey to toggle it is still not working either. I did toggle it back and forth without restarting when I played around after the first installation, so I don't know if that broke it / put it out of sync somehow.
edit /home/kkr/.config/MangoHud/MangoHud.conf

**Comment by kajlando** [comment]
> Is there a workaround when it doesn't work the opposite way? I want to enable the hud globally, but despite being toggled it is not showing up unless I use the prefix, and then the hotkey to toggle it is still not working either. I did toggle it back and forth without restarting when I played around after the first installation, so I don't know if that broke it / put it out of sync somehow.

edit ~/.config/MangoHud/MangoHud.conf

**Comment by benjamimgois** [comment]
@NaturalHate the only change that Global Enable does it add the line "export MANGOHUD=1" inside the folder `/home/$USER/.profile`. To disable just edit the .profile, remove that line and restart the system.

**Comment by NaturalHate** [comment]
> @NaturalHate the only change that Global Enable does it add the line "export MANGOHUD=1" inside the folder `/home/$USER/.profile`. To disable just edit the .profile, remove that line and restart the system.

I want it globally enabled, not disabled. That line is already present in that file though.



> > Is there a workaround when it doesn't work the opposite way? I want to enable the hud globally, but despite being toggled it is not showing up unless I use the prefix, and then the hotkey to toggle it is still not working either. I did toggle it back and forth without restarting when I played around after the first installation, so I don't know if that broke it / put it out of sync somehow.
> 
> edit ~/.config/MangoHud/MangoHud.conf

I'm not sure what you want me to edit there..?

**Comment by kajlando** [comment]
> I'm not sure what you want me to edit there..?

### Disable / hide the hud by deafult
no_display

**Comment by NaturalHate** [comment]
> > I'm not sure what you want me to edit there..?
> 
> .### Disable / hide the hud by deafult
> no_display

That option does not exist, and again, I want to globally _enable_ Mangohud, so that I do not have to use the prefix for every title.

**Comment by benjamimgois** [comment]
> I want it globally enabled, not disabled. That line is already present in that file though.

Sorry, i misunderstood you. Could you try to add those lines in `/home/$USER/.bash_profile` ? If that works i can make an update to fix it.

**Comment by NaturalHate** [comment]
> > I want it globally enabled, not disabled. That line is already present in that file though.
> 
> Sorry, i misunderstood you. Could you try to add those lines in `/home/$USER/.bash_profile` ? If that works i can make an update to fix it.

I can confirm that this seems to work. Thanks. :)

**Comment by benjamimgois** [comment]
Nice, i'll add it to the next release. Thanks for reporting.
