### ISSUE TITLE
Restore FPS only option. (fps_only)

### ISSUE THREAD

**Issue by Bitwolfies** [benjamimgois/goverlay#112]
Was lost with the UI overhaul, you can only set the one that contains what graphic API is in use along with the latency, not the one that simply displays the fps.

**Comment by benjamimgois** [comment]
@Bitwolfies , since i had rebuild a huge part of goverlay i hadn't re-implemented the quick layouts yet. But it still in the plans. I have a couple of days off work this month, will try to implement it.

**Comment by benjamimgois** [comment]
fixed in 1.2 release

**Comment by Bitwolfies** [comment]
Doesn't actually appear to work properly, the config doesn't use the specific fps_only option that mangohud provides.

All I was asking for was the return of fps_only as an option alongside the fps option.

**Comment by Bitwolfies** [comment]
To make things perfectly clear, fps:
![Screenshot_20240729_105605](https://github.com/user-attachments/assets/f7350517-2b2d-4208-aacc-c1b0d5b45db8)
fps_only:
![Screenshot_20240729_105651](https://github.com/user-attachments/assets/7d985f04-33ec-413d-9c47-6b43b7f69f03)

**Comment by benjamimgois** [comment]
Indeed, i need to disable the "engine" and "frame time". Will try to make a fix for that asap
