### ISSUE TITLE
New random boxes - UI is a mess

### ISSUE THREAD

**Issue by LiamDawe** [benjamimgois/goverlay#115]
Hey, so the UI has become quite a mess with the latest update. There's some random extra boxes by some of the options that don't seem to do anything and it's getting a bit overly cramped :(

https://imgur.com/a/fKe8Dho

**Comment by benjamimgois** [comment]
Hi @LiamDawe , the boxes are used to activate and deactivate the Graph for those options. Just hover the mouse over the box and it will give you a hint.

![image](https://user-images.githubusercontent.com/7688496/112138617-7fd36f00-8bb0-11eb-859b-dce8ca35ff98.png)

**Comment by LiamDawe** [comment]
On my system the boxes don't fit it and are on top of text. The UI could do with some cleaning up to make things like this more clear IMO.

**Comment by benjamimgois** [comment]
What Distro / Desktop are you on ?

**Comment by LiamDawe** [comment]
My bad, should have said.

Arch / MATE.

**Comment by benjamimgois** [comment]
Nice, thanks for reporting @LiamDawe . I guess that's one of the dificulties on GUI apps on Linux. What works in some desktops doesn't necesseraly works/looks the same in others. I usually only makes have testing on Gnome, i'll try to refact the UI for better suite other desktops.

**Comment by kajlando** [comment]
For now try older versions for example 0.4.2.

**Comment by benjamimgois** [comment]
i just tried 0.5 on Ubuntu Mate and Manjaro KDE. Everything is fine on Ubuntu Mate but not that great on Manjaro KDE. So it seems a problem more related to themes used on qt5. I'll made a small update and enhance the spacing between icons. Hope that's enough to solve the issues by the moment.

![image](https://user-images.githubusercontent.com/7688496/112193845-0dca4c80-8be7-11eb-8596-798136158836.png)

![image](https://user-images.githubusercontent.com/7688496/112195587-e5dbe880-8be8-11eb-82fa-4398e37aedea.png)

**Comment by benjamimgois** [comment]
I just made a quick fix. @LiamDawe could you try and see if it fix the issue on your side ? 

[goverlay_05_test.zip](https://github.com/benjamimgois/goverlay/files/6191926/goverlay_05_test.zip)

**Comment by Azertooth** [comment]
that's my hud on manjaro

![Screenshot_20210416_162746](https://user-images.githubusercontent.com/6460423/115039553-d93d6e00-9ed0-11eb-93ce-45f31ea091db.png)

**Comment by benjamimgois** [comment]
@Azertooth thanks for the report. I think i´ll recreate the graphs UI. It isn´t working well for lots of users. I´ll take a look as soon as possible, life as being busy lately.

**Comment by Azertooth** [comment]
thank you  for your time, I'll gladly wait the new update 
________________________________
Da: Benjamim Gois ***@***.***>
Inviato: mercoledì 21 aprile 2021 05:48
A: benjamimgois/goverlay
Cc: Azertooth; Mention
Oggetto: Re: [benjamimgois/goverlay] New random boxes - UI is a mess (#115)

@Azertooth thanks for the report. I think i´ll recreate the graphs UI. It isn´t working well for lots of users. I´ll take a look as soon as possible, life as being busy lately.

**Comment by benjamimgois** [comment]
@Azertooth and @LiamDawe could you check if the new interface in 0.5.1 solves the issue ? I guess the problem is related to different adjustments in QT themes across distros.

**Comment by LiamDawe** [comment]
Looks fine here on Gnome Shell.
