### ISSUE TITLE
No option to set temperature units to Fahrenheit

### ISSUE THREAD

**Issue by ggtylerr** [benjamimgois/goverlay#117]
Temperature (at least on MangoHUD) is set to Celsius, with no option to set it to Fahrenheit. Unfortunately my dumb American brain uses Imperial units instead of Metric, so I can't tell whether my GPU is burning or not. 

It is possible to configure the HUD file manually, but it looks like GOverlay removes the `temp_fahrenheit` variable whenever I save it from the app. Is it possible to add a checkbox for Fahrenheit? Thanks :)

EDIT: Seems like there's also no option to edit the Time Format, so `time` always displays in 24 hours.

**Comment by benjamimgois** [comment]
Hi @ggtylerr , i'll add it to my todo list. Such features were never requested, so it wasnt on my priority.

**Comment by benjamimgois** [comment]
fixed in 1.2 release
