### ISSUE TITLE
FPS limit toggle hotkey doesnt work.

### ISSUE THREAD

**Issue by Rebootcomputa** [benjamimgois/goverlay#119]
I am on the latest version of Mangohud and Goverlay 1.1.1 works great, except for the FPS limiter, I can set it up on goverley and disable it, but once enabled I can not toggle it or and off using the hotkey, every other hotkey works, logging, etc, only the FPS limit toggle doesnt work,

KDE Neon 6

**Comment by benjamimgois** [comment]
@Rebootcomputa could you try the latest GIT version ? It already has some fixes that will be released in 1.2

**Comment by Rebootcomputa** [comment]
I tried compiling it but am getting errors with Lazerus, so I dont mind waiting for the next build to come out.

**Comment by benjamimgois** [comment]
@Rebootcomputa maybe the text isn't clear enough. I used the mangohud notation.

**Shift_L** + F1 = **LEFT SHIFT** + F1

**Shift_R** + F1 = **RIGHT SHIFT** + F1

I'll add a hint message with this tip on 1.2

**Comment by Rebootcomputa** [comment]
> @Rebootcomputa maybe the text isn't clear enough. I used the mangohud notation.
> 
> **Shift_L** + F1 = **LEFT SHIFT** + F1
> 
> **Shift_R** + F1 = **RIGHT SHIFT** + F1
> 
> I'll add a hint message with this tip on 1.2

Sorry, I should of updated the message here, I updated mangohud and change some settings on the .conf file, however the goverlay GUI doesnt update the settings, so every time I open it I have to re-add the settings, I have manually modified mangohud.conf and have it running properly now.

Thank you.

**Comment by benjamimgois** [comment]
Sorry that goverlay doesn't work for you. Anyway i took a deeper look in 1.2 release just to make sure it's working.
