### ISSUE TITLE
Adding the PPA produces 404 not found error

### ISSUE THREAD

**Issue by Fatih20** [benjamimgois/goverlay#120]
After adding the PPA with `sudo add-apt-repository ppa:flexiondotorg/mangohud` `apt-update` is automatically triggered. It produces this error.
```
Err:30 http://ppa.launchpad.net/flexiondotorg/mangohud/ubuntu bionic Release                                                                    
  404  Not Found [IP: 91.189.95.85 80]
```

After it read the package lists, it produces this.
```
E: The repository 'http://ppa.launchpad.net/flexiondotorg/mangohud/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by benjamimgois** [comment]
I´ll take a look as soon as possible. Life as being busy lately.

**Comment by stephanlachnit** [comment]
This is not a bug. There are just no builds for bionic. The only real fix besides building yourself is updating your distro.

**Comment by benjamimgois** [comment]
Thanks @stephanlachnit , i guess that solves the mistery.
