### ISSUE TITLE
make fails and says "cannot find -lQt6Pas"

### ISSUE THREAD

**Issue by NJT145** [benjamimgois/goverlay#121]
it says that `/usr/bin/ld: cannot find -lQt6Pas: No such file or directory`. I already installed lQt6Pas as it mentioned at readme file. What should I do?

**Comment by benjamimgois** [comment]
what distro are you using ?

**Comment by NJT145** [comment]
Ubuntu 22.04.4 LTS

**Comment by benjamimgois** [comment]
try also installing the dev package:

https://github.com/davidbannon/libqt6pas/releases/download/v6.2.8/libqt6pas6-dev_6.2.8-1_amd64.deb

**Comment by NJT145** [comment]
it worked. Thanks for help
