### ISSUE TITLE
GOverlay fails to start on Fedora 34

### ISSUE THREAD

**Issue by robert-sandor** [benjamimgois/goverlay#122]
GOverlay fails to start on Fedora 34, installed with dnf as per instructions.

Launching from terminal yields:
```
❯ goverlay
QSocketNotifier: Can only be used with threads started with QThread
[FORMS.PP] ExceptionOccurred 
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $0000000000585053
  $0000000000563EA9
  $00000000006E90ED
  $00000000006E8ACD
  $00000000006E4C03
  $00000000005F1E61
  $00000000005F1D7B
  $000000000044B46A
  $000000000044A2E0
[FORMS.PP] ExceptionOccurred 
```

here's dnf info about the `goverlay` package as well
```
❯ dnf info goverlay 
Installed Packages
Name         : goverlay
Version      : 0.5
Release      : 1.fc34
Architecture : x86_64
Size         : 9.6 M
Source       : goverlay-0.5-1.fc34.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Project that aims to create a Graphical UI to help manage Linux overlays
URL          : https://github.com/benjamimgois/goverlay
License      : GPLv3+
Description  : GOverlay is an open source project aimed to create a Graphical UI to manage
             : Vulkan/OpenGL overlays. It is still in early development, so it lacks a lot of
             : features.
             : 
             : This project was only possible thanks to the other maintainers and
             : contributors that have done the hard work. I am just a Network Engineer that
             : really likes Linux and Gaming.
```

Let me know if there's any more information i can provide, and i can happily provide it.

**Comment by benjamimgois** [comment]
I think this error is related to wayland, try to run it with the following command.

`QT_QPA_PLATFORM=xcb goverlay --style fusion`

**Comment by robert-sandor** [comment]
> I think this error is related to wayland, try to run it with the following command.
> 
> `QT_QPA_PLATFORM=xcb goverlay --style fusion`

hey - thanks for the reply.
running it with `QT_QPA_PLATFORM=xcb` actually starts it succesfully. is this then only a fedora packaging issue ?

**Comment by benjamimgois** [comment]
Sorry for taking to long, life always get in the way.  This line will set xWayland as a fallback. It's set on by default in Manjaro and Ubuntu, myabe it's not on Fedora. You can add it to `/etc/environment` but it might be good warn the fedora package mantainer about it.
