### ISSUE TITLE
Delete the unused 1.10 tag

### ISSUE THREAD

**Issue by Antiz96** [benjamimgois/goverlay#122]
Hello,

A [1.10](https://github.com/benjamimgois/goverlay/releases/tag/1.10) tag was once created as a fix release but got shortly dropped/renamed in favor of the [1.1.1](https://github.com/benjamimgois/goverlay/releases/tag/1.1.1) one (this was done after I expressed some concerns in [that thread](https://github.com/benjamimgois/goverlay/pull/104#issuecomment-2016890703) about how such a version bump could be a potential source of issue for package managers of the different Linux distributions).

The `1.10` release is gone, but the tag itself is still there, which creates [false positives](https://gitlab.archlinux.org/archlinux/packaging/packages/goverlay/-/issues/1) with version checkers such as [nvchecker](https://github.com/lilydjwg/nvchecker) (which we use on Arch Linux side to keep track of new upstream releases for our packages). Indeed, the `1.10` tag is seen as the latest release while the actual latest one is `1.1.1`. It will also prevent people using such version checkers to be alerted in case of a new release, as the future `1.2` tag will be seen as lower as the `1.10` tag, an will thus not be detected as the latest release.

As this `1.10` tag is actually unused and could be a potential source of issue for the package maintainers of the goverlay package in the various Linux distribution (at least it is one for me on Arch Linux side :stuck_out_tongue_closed_eyes:) I was wondering if you could consider deleting it?

I remain available if needed :slightly_smiling_face:

**Comment by benjamimgois** [comment]
Ouch, didn't know that would create such problems. Will do it asap, thanks for the info !

**Comment by benjamimgois** [comment]
Tag deleted

**Comment by Antiz96** [comment]
Thanks a lot! :smile:
