### ISSUE TITLE
How to disable the predefined hotkeys?

### ISSUE THREAD

**Issue by Bigwee875** [benjamimgois/goverlay#124]
I love MangoHUD & GOverlay, lets me see the GPU temps properly!
I have a few issues though, and I'm not sure if it's a MangoHUD thing or a GOverlay thing.

I don't need the FPS toggle limit key. (F1) [Disabled via having only one limiter at 60FPS]
I don't need to Log. (Shift_L+F2)
I don't need to upload logs. (F5) [Disabled via checkbox]
I don't need to toggle the HUD. (Shift_R+F12)

Those predefined keys are however taking up my Function keys.
Checking the dropdown list says I _Have To_ have them assigned and active.
Can we get options so I can set blanks / disable those keys?

**Comment by benjamimgois** [comment]
Never though about that. Yes, i'll add a option to disable the keys for next release.

**Comment by Bigwee875** [comment]
Thank you so much!

**Comment by benjamimgois** [comment]
It's implemented in the latest git code.

**Comment by benjamimgois** [comment]
implemented in 1.2 version
