### ISSUE TITLE
Each time Goverlay is opened, time checkbox is turned on. 

### ISSUE THREAD

**Issue by n3thshan** [benjamimgois/goverlay#125]
As the title says, every time i open goverlay, the time metric is turned on no matter if i turned it off before. Im on fedora KDE wayland with the latest version of goverlay rpm. Nvidia driver 555.58.02 with GSP Firmware disabled if that matters.

**Comment by benjamimgois** [comment]
Hi @n3thshan , thanks for reporting. This is a bug i'll fix asap.

**Comment by benjamimgois** [comment]
Already fixed in the latest git code, it will arrive in the next stable release.
