### ISSUE TITLE
Goverlay versionning

### ISSUE THREAD

**Issue by Xdavius** [benjamimgois/goverlay#127]
Hi =)

Small issue with goverlay versionning.

Was x.x.x for 1.1.1
now it's formated as x.x

Should be good for packagers to have x.x.x versionning to avoid conflicts (should be 1.2.0 so)

Thank you. 

I'm upgrading pacstall repository now.

regards

**Comment by benjamimgois** [comment]
Hi @Xdavius , actually 1.1.1 was a mistake of mine. I'll erase the tag 1.1.1. For now on, we will keep the versioning in 1.x. Thanks for reporting !

**Comment by Xdavius** [comment]
> Hi @Xdavius , actually 1.1.1 was a mistake of mine. I'll erase the tag 1.1.1. For now on, we will keep the versioning in 1.x. Thanks for reporting !

Hi,

Sorry for the double close, missclick :)

Ok for versioning. I will change to x.x for 1.3.

1.2(.0) is now available on pacstall as goverlay-bin and from source as goverlay.

I have also fixed the theme using qt6ct for all users.

Have a nice day :)
