### ISSUE TITLE
FPS Limiter

### ISSUE THREAD

**Issue by LGFugler** [benjamimgois/goverlay#127]
Just wondering if there is  there any reason why the upper FPS limit is 200.

I have a 240hz monitor and would like to cap at around 300, have tried editing the config file to override but it doesnt work.

Is this a feature you would consider changing please.

Thanks :smile:

**Comment by benjamimgois** [comment]
@LGFugler , as i never had a high refresh monitor i don't know what kind of values users want. Tell me what frequencies do you like to have and i'll implement on the next version

**Comment by LGFugler** [comment]
Sounds good- Potentially some new FPS caps at 240, 300, 360 and 420? Covers both exact FPS capping for 240hz and 360hz users and an option for headroom on both?

**Comment by benjamimgois** [comment]
Ok, i'll note it down.

**Comment by benjamimgois** [comment]
Fixed in 0.6 release
