### ISSUE TITLE
Goverlay doesn't properly spawn Vkcube under KDE Wayland

### ISSUE THREAD

**Issue by salixor** [benjamimgois/goverlay#129]
When I start Goverlay on Wayland (KDE Plasma 6.1), I am getting the following result :

![image](https://github.com/user-attachments/assets/caa9eb8f-2030-4672-a961-6cd68bf8f3b3)

Closing Goverlay keeps this window open, with no means to close it all.

The only warning log I am seeing is this : `qt.core.qobject.connect: QObject::disconnect: No such slot QComboBox::_q_returnPressed()`

However, starting Vkcube by itself properly works.

**Comment by benjamimgois** [comment]
What distro are you running ?  How do you install vkcube ? All the tests are done using the vulkan-tools package.

**Comment by madic-creates** [comment]
I've got the same problem

- KDE Plasma 6.1.3
- Wayland
- Nvidia 555.58.02
- EndeavourOS (Arch based)
- Kernel 6.10.2

The same combination works under x11

Installed goverlay via package manager from arch extra repository. vkcbue gets installed as dependency

**Comment by salixor** [comment]
Here are additional infos :
- KDE Plasma 6.1.3 (Wayland)
- Nvidia 555.58.02
- Manjaro (Kernel 6.6.44)
- Goverlay from the extra repos, vkcube from vulkan-tools as a dependency

**Comment by benjamimgois** [comment]
Strange.... i'm on kde + wayland + endeavour but i have a AMD gpu. Could you run in a terminal "mangohud vkcube" and post here the results ?

**Comment by salixor** [comment]
Ah, we found the culprit! It does error out.

```
Selected GPU 0: NVIDIA GeForce RTX 3070 Ti, type: DiscreteGpu
Authorization required, but no authorization protocol specified

[2024-08-04 22:00:14.636] [MANGOHUD] [error] [nvctrl.cpp:56] XNVCtrl didn't find the correct display
```

Seems like it's an NVIDIA issue (they are so rare!), already reported on MangoHud's Github : https://github.com/flightlessmango/MangoHud/issues/1357

**Comment by benjamimgois** [comment]
Good to know, let's hope the new open modules will fix this issues. Thanks for reporting
