### ISSUE TITLE
SUGGESTION: vkBasalt GUI implementation

### ISSUE THREAD

**Issue by TheEvilSkeleton** [benjamimgois/goverlay#13]
Hello, I know a very good tool you can make a GUI for. It is made by [DadSchoorse](https://github.com/DadSchoorse) and it is called [vkBasalt](https://github.com/DadSchoorse/vkBasalt).

**Comment by benjamimgois** [comment]
@TheEvilSkeleton the version 0.3 that i just release has initial implementation for vkBasalt. Hope you like it

**Comment by TheEvilSkeleton** [comment]
Now this is awesome

**Comment by TheEvilSkeleton** [comment]
@benjamimgois I created an issue there, hope he accepts it: https://github.com/DadSchoorse/vkBasalt/issues/72
