### ISSUE TITLE
Preview does not close with the rest of the program

### ISSUE THREAD

**Issue by rasmusq** [benjamimgois/goverlay#130]
Whenever I need to close goverlay, the preview keeps itself open.
The only way I can make the preview close with the program is if I run it in a terminal and quit it from the terminal with CTRL+C.
This leads to many previews to keep being open when I am trying to tweak things ingame.

These are my specs:
OS: Arch Linux x86_64
Host: B550 AORUS ELITE V2
Kernel: Linux 6.10.3-arch1-1
Uptime: 1 hour, 44 mins
Packages: 880 (pacman), 10 (flatpak)
Shell: fish 3.7.1
Display (Mi Monitor): 3440x1440 @ 120 Hz in 34″ [External]
WM: Hyprland (Wayland)
Cursor: Bibata-Modern-Classic (24px)
Terminal: alacritty 0.13.2
Terminal Font: alacritty (16pt)
CPU: AMD Ryzen 5 5600X (12) @ 3.70 GHz
GPU: AMD Radeon RX 6800 XT [Discrete]
Memory: 4.65 GiB / 31.27 GiB (15%)
Swap: 256.00 KiB / 4.00 GiB (0%)
Disk (/): 565.61 GiB / 953.37 GiB (59%) - btrfs
Local IP (eno1): 192.168.1.204/24
Locale: en_US.UTF-8

![image](https://github.com/user-attachments/assets/1743ea0d-dc78-44ac-a52e-003895de4337)

**Comment by benjamimgois** [comment]
@rasmusq this is indeed the correct behavior for the current build. Goverlay executes vkcube in a separated process, so they are independent. I plan to recreate vkcube using DXVK inside goverlay in a future build, we won't need vkcube anymore.

**Comment by rasmusq** [comment]
Sounds like a great solution to me!
