### ISSUE TITLE
vaapi isn't an option for replay-sorcery

### ISSUE THREAD

**Issue by zeko9381** [benjamimgois/goverlay#131]
I tried choosing VAAPI for the encoder option for replay-sorcery, so GOverlay wrote `videoEncoder = vaapi` in the conf file. Replay-sorcery supports `vaapi_h264` and `vaapi_hevc`.

**Comment by benjamimgois** [comment]
Hi @zeko9381 , by the time i wrote the app replaysorcery was in 0.5 version. The documentation only reference the `vaapi` option, i'll try to update it for the next release. Thanks for reporting

**Comment by benjamimgois** [comment]
Fixed in 0.6 release
