### ISSUE TITLE
[Feature] Implement Wayland support

### ISSUE THREAD

**Issue by iMonZ** [benjamimgois/goverlay#135]
When I force running this tool in Wayland mode, I get this error 

>  ~  goverlay
> Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
> QSocketNotifier: Can only be used with threads started with QThread
> [FORMS.PP] ExceptionOccurred 
>   Sender=EAccessViolation
>   Exception=Access violation
>   Stack trace:
>   $0000000000576F7B
> [FORMS.PP] ExceptionOccurred 

I could use x11 mode, but this doesn't work since X11 apps can't access Wayland apps

**Comment by benjamimgois** [comment]
@iMonZ right now the only way to use goverlay on wayland is forcing the X11 mode with:

`QT_QPA_PLATFORM=xcb goverlay --style fusion`

Unless this is implemented in Lazarus itself, i don't see this being fixed anytime soon.
