### ISSUE TITLE
vkBasalt config

### ISSUE THREAD

**Issue by X6205** [benjamimgois/goverlay#136]
Hi,

I'm not sure if this issue is in Goverlay or in vkBasalt itself, but if i open in Goverlay tab of vkBasalt and click on "Sync" (what will downdload ReShade shaders) and then i click on "Save", what will propably create configuration file for vkBasalt. And in this configuration file is incomplete. Error in first lines. While /textures path is defined properly, path for /shaders is missing. To be more specific, last part of the path, the "/shaders" word is not written in that config file. I hope you understand what i mean.

Wel.. as i have said, i'm not sure if this issue is in Goverlay generating incomplete config file or it's some kind of error in vkBasalt.

Thank you.

**Comment by benjamimgois** [comment]
@X6205 you're right. Since it isn't a function a use a lot myself, I completely miss that. I already fix it on the latest code, will upload it soon in a new release. Thanks for reporting.

**Comment by benjamimgois** [comment]
Fixed in 0.6.2
