### ISSUE TITLE
Test button does not work in MangoHud tab no glxgears nor vkcube

### ISSUE THREAD

**Issue by sabotendarsama** [benjamimgois/goverlay#137]
Im working in a linux distro to only play games in GOverlay version 0.5.1 the "run" button works great but in the new 0.6.1 does not work

![print_2021-08-17_00 06 48](https://user-images.githubusercontent.com/52870659/129657590-83726dd3-89ba-43f0-8dd1-8b840305d844.png)

**Comment by benjamimgois** [comment]
Hi @sabotendarsama , there was no changes on the execution script on 0.6.1, it basically execute "mangohud vkcube & mangohud glxgearss". Can you try to run this commands on the terminal ? On your screenshot there's a message that none of the dependencies are installed. Are you sure mangohud is installed ?

**Comment by sabotendarsama** [comment]
Hi in VkBasalt tab vkcube works great see the prints above
![print_2021-08-17_17 29 26](https://user-images.githubusercontent.com/52870659/129796275-33183962-5a4a-47dc-969c-29aef141ffb8.png)
![print_2021-08-17_17 29 31](https://user-images.githubusercontent.com/52870659/129796295-efa6bba8-7462-4950-abef-d4d27b9d478a.png)
 here you can comprove the glxgears and vkcube works great
![print_2021-08-17_17 31 43](https://user-images.githubusercontent.com/52870659/129796529-8b2a56d6-fa7f-4df5-9844-e74e50962ef9.png)
![print_2021-08-17_17 31 37](https://user-images.githubusercontent.com/52870659/129796711-63b71056-952f-4734-bef0-c9df541a1f83.png)
![print_2021-08-17_17 33 16](https://user-images.githubusercontent.com/52870659/129796598-cbdcf8e2-6066-4c77-b2c3-c769b9bd1951.png)

**Comment by benjamimgois** [comment]
@sabotendarsama in the vkbasalt tab the run button executes "ENABLE_VKBASALT=1 vkcube". The problem seems to be on the mangohud installation, could you try "mangohud vkcube" in a terminal and post the results ?

**Comment by sabotendarsama** [comment]
@benjamimgois i found the problem, in my system the mangohud is working inside a folder "/opt/MangoHud" in any calls we have to export PATCH to this location, the curious thing is in the GOverlay 0.5.1 this is not necessary, anyway the problem has been solved 👍 
![print_2021-08-19_21 07 01](https://user-images.githubusercontent.com/52870659/130159315-488b5688-df26-4abe-ad30-7f5828bb7b64.png)
