### ISSUE TITLE
Cannot set custom FPS value

### ISSUE THREAD

**Issue by hombiebearcat** [benjamimgois/goverlay#138]
Not sure if this is a bug or just unimplemented as of now, but if I set my FPS to Custom it remains locked at 1 in the Custom FPS box, with the box greyed out and no way to change it.

**Comment by benjamimgois** [comment]
It's a bug.... i think i know when i screw it... I'll fix it asap. Thanks for the report

**Comment by benjamimgois** [comment]
Fixed in 0.6.3

**Comment by JakeDevs** [comment]
i know this issue is closed but this is happened to me
