### ISSUE TITLE
Error: (lazarus) invalid Lazarus directory "": directory lcl not found

### ISSUE THREAD

**Issue by TheEvilSkeleton** [benjamimgois/goverlay#14]
Greetings, so I have followed issue #4, but executing the command 

    lazbuild --lazarusdir=/usr/lib/lazarus -B goverlay.lpi

did not work. I also made a directory in `/usr/lib/lazarus`, and running the command still did not work. I then created some new directories and it still ended up not working.

![image](https://user-images.githubusercontent.com/50847364/78736364-7b308f00-793c-11ea-95cc-93ab4f01abac.png)

**Comment by yochananmarqos** [comment]
Please do not post screenshots. Instead, post logs wrapped in code tags using the Insert code button: <kbd><></kbd>

What distro are you using? No matter what it is, you should not be manually creating directories in `/`. You'll eventually run into problems.

**Comment by TheEvilSkeleton** [comment]
> Please do not post screenshots. Instead, post logs wrapped in code tags using the Insert code button: <>

Sorry, I'm really new at this. How do I do that?

> What distro are you using? 

Gentoo

Do you have `lazarus` installed?

Yes

If you do, `/usr/lib/lazarus/` is already there. No matter what distro, you should not be manually creating directories in `/`. You'll eventually run into problems.

Alright

**Comment by yochananmarqos** [comment]
> Sorry, I'm really new at this. How do I do that?

![Screenshot from 2020-04-07 20-11-50](https://user-images.githubusercontent.com/5437803/78737461-c2069080-790c-11ea-95a0-77d401df8834.png)


On Gentoo, you can run this command to see where `lazarus` is installed:

```
equery f lazarus
```

**Comment by TheEvilSkeleton** [comment]
> EDIT: If you're really that new at things, why are you using Gentoo to begin with? Especially if you get frightened off so easily.

I use Gentoo because I like the freedom it offers. Though I got frightened off so easily mainly because the Lazarus package is one or two versions behind, and I do not want to give my real name to the maintainers just so I can maintain the package. I also do not feel like using Bugzilla since it is too complicated to use.

**Comment by yochananmarqos** [comment]
If you say so. I'm trying to help, but you're not being very helpful. There's no reason why the `--lazarusdir` flag wouldn't work if `lazarus` is installed properly.

**Comment by TheEvilSkeleton** [comment]
You're right, it was an asshole move of me. I just ran
```equery f lazarus```
and it gave me this: [equery.txt](https://github.com/benjamimgois/goverlay/files/4448026/equery.txt)

**Comment by TheEvilSkeleton** [comment]
Alright, so I just tried using Lazarus 2.0.6 from an overlay, and the same issue still appears.

Here is the new output of `equery f lazarus`: [lazarus.txt](https://github.com/benjamimgois/goverlay/files/4448053/lazarus.txt)

Also, here are my hardware info: [hardware.txt](https://github.com/benjamimgois/goverlay/files/4448068/hardware.txt)

**Comment by yochananmarqos** [comment]
Apparenlty Gentoo uses `/usr/share/` instead of `/usr/lib`, so use:

``
lazbuild --lazarusdir=/usr/share/lazarus -B goverlay.lpi
```

**Comment by TheEvilSkeleton** [comment]
Alright, so I got a new error, but it seems like it has fixed one issue:
![image](https://user-images.githubusercontent.com/50847364/78742890-a622df00-794c-11ea-8925-cb5cb5383e4c.png)

Probably I have to run it as root? I will wait for you to clarify it.

**Comment by yochananmarqos** [comment]
Again, please do not post screenshots. Ugh.

**Comment by TheEvilSkeleton** [comment]
Sorry

**Comment by yochananmarqos** [comment]
Of course you would need to run it as root. However, that's not a good idea. I would write your own ebuild to install it properly. I've seen others use Arch PKGBUILDs as inspiration since they're not too dissimilar. He's my Arch User Repository (AUR) package: [`goverlay-git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=goverlay-git)`.

**Comment by TheEvilSkeleton** [comment]
That is the thing, all I know is bump ebuilds, but writing them isn't something I enjoy(ed) (I tried it before and completely gave up). On top of that, I will have to write ebuilds for MangoHud and vkBasalt, which I have tried to do so with my friends, but we have no experience with Vulkan.

Sorry for breaking your head

**Comment by yochananmarqos** [comment]
I understand, I've been there. That's how I got the motivation to write my own PKGBUILDs. 

"I want this package, but it requires one one more packages not in the repos or AUR." 

"I want to install this package, but the PKGBUILD is broken / outdated and the package maintainer is AWOL."

**Comment by TheEvilSkeleton** [comment]
I also got the motivation to write my own ebuild, but not being able to understand it was what made me give up (same with Python, C++, Rust and JavaScript)

**Comment by yochananmarqos** [comment]
I admit I have gift with computers, but I can't program at all. I neither have the attention span nor memory. I'm always looking back at wiki's, tutorials and my notes to remember what the heck I was doing. However, I can figure out how to read any code language and learn what things do if I focus. Weird, eh?

If you don't end up making a Gentoo package, I'm sure someone else well eventually for a cool project like this.

**Comment by TheEvilSkeleton** [comment]
> I admit I have gift with computers

Same here.

> Weird, eh?

Very weird, but awesome too. I have a gift with documentations, which is why I mostly contribute in documentations. Though when it comes to programming, I give up within a couple of days.

> If you don't end up making a Gentoo package, I'm sure someone else well eventually for a cool project like this.

I hope someone will, though Gentoo is nearly dead; it isn't a bleeding edge distro anymore since the latest packages aren't in the repos (like you have seen with Lazarus), and there are still no official ebuilds for a lot of stuff related to gaming.

**Comment by stephanlachnit** [comment]
@benjamimgois if you haven't seen it yet:

> Feel free to close the issue.

**Comment by benjamimgois** [comment]
Ops, thanks for pointing @stephanlachnit .

**Comment by TheGreatMcPain** [comment]
@TheEvilSkeleton Found out about this project yesterday, and decided to throw together an [ebuild.](https://github.com/TheGreatMcPain/TheGreatMcPain-overlay/blob/master/games-util/goverlay/goverlay-9999.ebuild)

I was wondering if you, or other gentoo users, could test it out.  I also have mangohud in my overlay, and will try to get a vkBasalt ebuild put together at some point.

I did have to copy the contents of `/usr/share/lazarus` into portage's working directory in order to please portage's sandbox, but works more or less.

**Comment by TheEvilSkeleton** [comment]
> @TheEvilSkeleton Found out about this project yesterday, and decided to throw together an [ebuild.](https://github.com/TheGreatMcPain/TheGreatMcPain-overlay/blob/master/games-util/goverlay/goverlay-9999.ebuild)
> 
> I was wondering if you, or other gentoo users, could test it out. I also have mangohud in my overlay, and will try to get a vkBasalt ebuild put together at some point.
> 
> I did have to copy the contents of `/usr/share/lazarus` into portage's working directory in order to please portage's sandbox, but works more or less.

@TheGreatMcPain Unfortunately, I can't really test it anymore because my Gentoo install has been moved to a directory (chroot) so I can still contribute to Gentoo without needing to have a proper Gentoo install. It is still great that your MangoHud and GOverlay ebuilds are in your repositories. As for vkBasalt, there are already some [ebuilds](https://github.com/pchome/vulkan-gentoo-overlay/tree/master/media-libs/vkbasalt) (outdated) that I have found that you can inspire yourself.

It's great to see you here: https://gpo.zugaina.org/games-util/mangohud
