### ISSUE TITLE
Custom Shaders not recognized in goverlay's list or generated .conf files

### ISSUE THREAD

**Issue by V-Copy** [benjamimgois/goverlay#140]
Basically the title. My shaders are in the same folder as the sync'd ReShade shaders, and I modified two vkBasalt.conf files in ~/.config/goverlay/ and ~/.config/vkBasalt/ both to no avail. I'm running the latest version of goverlay and I just can't seem to be able to add any shaders that aren't already part of the synchronized ones. I've also been trying hard to find any tutorials or walkthroughs, but nothing seems to exist, even other closed/open issues.
Thanks for any help.

**Comment by benjamimgois** [comment]
@V-Copy Custom files won't be recognized inside the goverlay GUI and it's not on the horizon to implement. My best advise would be to search for this feature vkbasalt documentation.
