### ISSUE TITLE
IMPROVEMENT: Add a scroll bar to the GUI

### ISSUE THREAD

**Issue by Zeioth** [benjamimgois/goverlay#143]
When a fixed size is forced to the program window, some elements won't be vissible. This could be fixed by adding an scrollbar.

**Comment by benjamimgois** [comment]
I'll investigate it. I know the actual state will give us a hard time om steam deck screen.

**Comment by benjamimgois** [comment]
This won't be needed with the new UI. Thanks for reporting.
