### ISSUE TITLE
Are `mesa-demos` & `vulkan-tools` still prerequisites?

### ISSUE THREAD

**Issue by kira-bruneau** [benjamimgois/goverlay#145]
Since the 0.6.2 update, there's no longer any way to run `glxgears` & `vkcube` from goverlay's UI, even though the code to launch them still exists in the repo. Should these prerequisities be removed?

`glxgears` might be redundant now with the live OpenGL preview, but I think it would still be useful to keep `vkcube` to verify that MangoHud works with Vulkan. Or maybe even embed a live Vulkan preview?

**Comment by benjamimgois** [comment]
Hi @kira-bruneau , indeed the glxgears isn't needed anymore. Vkcube is still used in vkbasalt tab. If you think it's still usefull, i can add a vkcube button for mangohud again. A vulkan live preview will be very dificult, since the only implementation of vulkan for pascal is still very new.

**Comment by kira-bruneau** [comment]
>  Vkcube is still used in vkbasalt tab.

Oh right, I forgot about that :stuck_out_tongue:. Thanks!

> A vulkan live preview will be very dificult, since the only implementation of vulkan for pascal is still very new.

Ah, it didn't seem like it would be easy to implement.

> If you think it's still usefull, i can add a vkcube button for mangohud again.

I think it would be nice to have the vkcube option, just as a sanity check for Vulkan, but it's not really that important. I was mostly just curious if we still needed these prerequisites.
