### ISSUE TITLE
Add a link to this github in the "About" section

### ISSUE THREAD

**Issue by GitThisBugOff** [benjamimgois/goverlay#151]
Currently it shows links to MangoHud/VKBasalt/ReplaySorcery. Adding a link to this project makes it a bit easier for users to find us.

**Comment by benjamimgois** [comment]
It was added in 0.6.3. There's a small text alignment problem, but it's a small fix.

![image](https://user-images.githubusercontent.com/7688496/136789785-c9bb690d-2d81-4a0e-a266-316411aaf3dc.png)
