### ISSUE TITLE
Fail to launch - Debian 11

### ISSUE THREAD

**Issue by GileonFletcher** [benjamimgois/goverlay#158]
Running Debian 11 Testing (X11) with Goverlay installed through Synaptic (0.6.3-2). Running Goverlay in the terminal outputs the following:

> [FORMS.PP] ExceptionOccurred 
  Sender=Exception
  Exception=Could not find FB config
  Stack trace:
  $000000000060A6C4
  $00000000006004A3
  $0000000000559A75
  $0000000000559220
  $000000000055A9D8
  $0000000000559D3F
  $0000000000559220
  $000000000055A9D8
  $0000000000559D3F
  $000000000042EE27
  $0000000000437AED
  $0000000000438E18
  $0000000000559220
  $000000000055A9D8
  $0000000000440CFB

I attempted running the command from the readme for building from source ("Starting in 0.6.2...") just for the sake of it which outputs that ./goverlay doesn't exist. I have reinstalled (and even used the software center to install) without much luck. I am uncertain if this is a byproduct of Debian testing, something strange with my system, or otherwise. Thanks in advance.

**Comment by benjamimgois** [comment]
@GileonFletcher , this error is a indication that it mught be running under wayland. Please, try to run goverlay with the following command:

`QT_QPA_PLATFORM=xcb mangohud --dlsym goverlay --style fusion`

the next release will have a new start script to mitigate this issue.

**Comment by GileonFletcher** [comment]
Unfortunately that command yields the exact same text output as previously posted.

**Comment by benjamimgois** [comment]
After the last update on the startup script, several people are relating problems. @stephanlachnit do you have any clue of what might be the problem ?

**Comment by stephanlachnit** [comment]
Hm, I can't test it right now, but can you try to install 0.6.4-1 from unstable? Migration is blocked right now due to a Lazarus bug.

Link: https://packages.debian.org/sid/amd64/goverlay/download


And you send the log for make?

**Comment by GileonFletcher** [comment]
Hopefully this is what you're after... not something I do every day.

[goverlaylog.txt](https://github.com/benjamimgois/goverlay/files/7534884/goverlaylog.txt)

**Comment by stephanlachnit** [comment]
> Hopefully this is what you're after... not something I do every day. Same error as originally stated occurs.
> 
> [goverlaylog.txt](https://github.com/benjamimgois/goverlay/files/7534884/goverlaylog.txt)

Ok, that's weird. Can you run `./start_goverlay.sh` in that folder and paste the logs? Because from the logs it seems like `./goverlay` should exist.

**Comment by GileonFletcher** [comment]
Attached screenshot just for more 'direct' evidence.

![Screenshot from 2021-11-15 03-54-07](https://user-images.githubusercontent.com/94220011/141760768-ed4759ce-5093-4dc1-b200-df6af5ada944.png)

**Comment by stephanlachnit** [comment]
Ok so this is definitely an error on your side. Can you try it without `sudo`? The file is clearly in the folder.

**Comment by GileonFletcher** [comment]
Without sudo, any command variation of running goverlay within the folder gives the same error as the original post but with a slightly different stack trace. I very well might be doing something wrong, but the way the average user would install it still gives the same error (at least for me). I have since tried it on another machine running Fedora 35 installed from the primary repo with the same error. Using the version from Debian stable (0.4.4-1) does work.

**Comment by benjamimgois** [comment]
@GileonFletcher , did you try the .tar.xz file ? Just extract the file and run the .sh file. Post the results here, please. I can´t reproduce this issue on Manjaro and in a arch install.

**Comment by GileonFletcher** [comment]
Something different for a change.

> [FORMS.PP] ExceptionOccurred 
  Sender=Exception
  Exception=Could not find FB config
  Stack trace:
  $00000000007C6974  LOPENGLCREATECONTEXT,  line 333 of glqtcontext.pas
  $00000000007B6123  CREATEHANDLE,  line 697 of openglcontext.pas
  $000000000062A405  CREATEWND,  line 7537 of include/wincontrol.inc
  $0000000000629BB0  CREATEHANDLE,  line 7447 of include/wincontrol.inc
  $000000000062B368  HANDLENEEDED,  line 7900 of include/wincontrol.inc
  $000000000062A6CF  CREATEWND,  line 7582 of include/wincontrol.inc
  $0000000000629BB0  CREATEHANDLE,  line 7447 of include/wincontrol.inc
  $000000000062B368  HANDLENEEDED,  line 7900 of include/wincontrol.inc
  $000000000062A6CF  CREATEWND,  line 7582 of include/wincontrol.inc
  $000000000044CDB7  CREATEWND,  line 23 of include/scrollingwincontrol.inc
  $00000000004565FD  CREATEWND,  line 2703 of include/customform.inc
  $0000000000457BF8  CREATEWND,  line 3171 of include/customform.inc
  $0000000000629BB0  CREATEHANDLE,  line 7447 of include/wincontrol.inc
  $000000000062B368  HANDLENEEDED,  line 7900 of include/wincontrol.inc
  $000000000046209B  CREATEFORM,  line 2254 of include/application.inc
  $0000000000424022  main,  line 21 of goverlay.lpr

**Comment by benjamimgois** [comment]
> Something different for a change. This was on the Debian 11 testing. Edit: exact same output on Fedora 35.
> 
> > [FORMS.PP] ExceptionOccurred
> > Sender=Exception
...

Do you have `qt5pas` dependency installed ?

**Comment by GileonFletcher** [comment]
Yes, `libqt5pas1` is installed as version `2.6+2.0.8+dfsg-2`. I just tried reinstalling the package with no change in the result.

**Comment by GileonFletcher** [comment]
Grabbed another laptop still running Debian 11 stable and manually installed the latest release. Runs without issue. Perhaps an issue with something in the current Debian testing? Running it on stable does give me the error:

`QWidget::paintEngine: Should no longer be called paint`

but other than that it runs fine.

**Comment by stephanlachnit** [comment]
> Grabbed another laptop still running Debian 11 stable and manually installed the latest release. Runs without issue. Perhaps an issue with something in the current Debian testing?

Which version of GOverlay?

> Running it on stable does give me the error:
> 
> `QWidget::paintEngine: Should no longer be called paint`
> 
> but other than that it runs fine.

This is nothing Debian specific afaik.

**Comment by benjamimgois** [comment]
> `QWidget::paintEngine: Should no longer be called paint`

This error is Lazarus related, it can be ignored for now. It's related to a LCL command that's being deprecated if i remember correctly.

**Comment by GileonFletcher** [comment]
> Which version of GOverlay?
The latest version from Github, 0.6.4

**Comment by stephanlachnit** [comment]
> > Which version of GOverlay?
> 
> The latest version from Github, 0.6.4

Hm, that's actually really weird.

**Comment by stephanlachnit** [comment]
@GileonFletcher can you try it now?

**Comment by benjamimgois** [comment]
I guess we can close this issue. @GileonFletcher if the problem still exist you can open again.
