### ISSUE TITLE
App rendering problem

### ISSUE THREAD

**Issue by Shuna322** [benjamimgois/goverlay#16]
I was able to use the app before but it just broke completely, maybe with an update.

System info:
Distro: Manjaro KDE with all the latest updates
Nvidia Driver Version: 515.57
Reboot and reinstall didn't help
Install type: Arch AUR 0.9.0-1

![image](https://user-images.githubusercontent.com/32617699/184711283-7affd354-69c9-4dc3-aabb-a071d322e1af.png)

**Comment by benjamimgois** [comment]
What theme are you using ? Could you try to run it forcing the breeze theme ?

`goverlay --style breeze`

**Comment by Shuna322** [comment]
I'm using Edna theme, but forcing breeze didn't help. Also getting lots of junk logs `paint`
![image](https://user-images.githubusercontent.com/32617699/184914630-6d4c729a-5d7d-425f-ad35-425e5a8dc4eb.png)
Here is also some logs that I was able to catch
![image](https://user-images.githubusercontent.com/32617699/184914903-7a9e6915-7954-4d1b-b398-ed6da3092ac6.png)

**Comment by hiraga73** [comment]
I have the same problem, in Big Linux ( manjaro kde)

**Comment by Poldovico** [comment]
Same thing happening to me in Garuda Dr460nized

`--style breeze` fixes it for me, though I do get the `paint` spam in terminal.

Garuda uses a customized Sweet called Sweetified Plasma by default, though interestingly even switching to Breeze from my KDE settings still gave me the broken GUI, even though launching it as `goverlay --style breeze` worked right.

**Comment by Shuna322** [comment]
Setting theme to breeze didn't resolve issue for me

**Comment by benjamimgois** [comment]
Guys, these kind of problems are usually related to Kvantum and other apps that changes the distro native look (forcing blur and transparency) . Try to disable it and try again.

**Comment by jlucaso1** [comment]
I have the same problem, in Manjaro (kde, nvidia)

**Comment by Shuna322** [comment]
Fixed by adding goverlay to Kvantum Opaque apps list
![image](https://user-images.githubusercontent.com/32617699/188428890-37ccac66-e0cd-4a31-9a19-b35d6cd45fb5.png)
![image](https://user-images.githubusercontent.com/32617699/188428939-4d73facc-1733-47b2-b0cb-ff9dc602e3f1.png)
