### ISSUE TITLE
About page is not scaling well on a 1920x1080 display

### ISSUE THREAD

**Issue by Netherquark** [benjamimgois/goverlay#163]
![image](https://user-images.githubusercontent.com/65618735/143664678-8e4e877c-c267-461a-910e-9e28f24da81d.png)
Using:
Wayland
Gnome 41
Fedora 35
1920x1080 display
![image](https://user-images.githubusercontent.com/65618735/143664719-763ae5ba-f1a8-4961-81e7-3516191ceeb5.png)

**Comment by benjamimgois** [comment]
I guess that's fixed in 0.7, could you try ?

**Comment by Netherquark** [comment]
fedora repos stuck on 0.6.4 :(

**Comment by benjamimgois** [comment]
Just made some new tweaks in 0.7.1. This is how it looks in Fedora 35 now. Thanks for reporting.

![image](https://user-images.githubusercontent.com/7688496/146291391-0277d9ac-0deb-426e-a6a5-ce7d7e04b2e8.png)
