### ISSUE TITLE
Not possible to maximise/minimise GOverlay window

### ISSUE THREAD

**Issue by Netherquark** [benjamimgois/goverlay#164]
![image](https://user-images.githubusercontent.com/65618735/143664905-34eb7743-1420-4b0b-a87b-6a02fda40516.png)

Using:
Wayland
Gnome 41
Fedora 35
1920x1080 display

![image](https://user-images.githubusercontent.com/65618735/143664916-4180e6bf-c5a1-470a-ab96-697dc4a802fa.png)
![image](https://user-images.githubusercontent.com/65618735/143664938-dd4eec4b-fafe-4380-b423-512256eed9d2.png)

**Comment by benjamimgois** [comment]
This is by design. It won't change in a near future, but with the new UI it shouldn't be needed.

Sorry
