### ISSUE TITLE
Looks horrible on Adwaita / Fusion

### ISSUE THREAD

**Issue by stephanlachnit** [benjamimgois/goverlay#165]
This is how version 0.7 looks on Gnome currently:
![Screenshot from 2021-11-29 21-34-46](https://user-images.githubusercontent.com/36662302/143940620-ad10ea3d-912b-4db0-8afd-4bdd1cf5ce4a.png)

I think the problem here is the theme. Fusion doesn't seem to be a proper theme but rather uses the system default one. Since I think you use KDE and thus the Breeze theme (KDE default) or a theme based on it, it's best to force this theme IMHO. How it looks for me:
![Screenshot from 2021-11-29 21-46-29](https://user-images.githubusercontent.com/36662302/143940624-01311cf3-fa67-4821-876b-6141f6f12cca.png)

I'll open a PR.

**Comment by benjamimgois** [comment]
Good catch @stephanlachnit . Already merge the commits. Check if it's fixed now please.

**Comment by stephanlachnit** [comment]
Ah shoot, I missed a `chmod +x start_goverlay.sh`

**Comment by benjamimgois** [comment]
I think we might have to revert the commit, now other parts of the interface are broken. Also the images to each category aren't loading correctly. 

![image](https://user-images.githubusercontent.com/7688496/143947579-b1046e8a-5bd4-4ad7-9e51-0aef3d456123.png)

> 
> I think the problem here is the theme. Fusion doesn't seem to be a proper theme but rather uses the system default one. Since I think you use KDE and thus the Breeze theme (KDE default) or a theme based on it, it's best to force this theme IMHO. How it looks for me: ![Screenshot from 2021-11-29 21-46-29](https://user-images.githubusercontent.com/36662302/143940624-01311cf3-fa67-4821-876b-6141f6f12cca.png)
> 
I think that there's nothing wrong with fusion, by default the adwaita theme being used is the "white" one, you need to force the dark version so it doesn't look like that. In Manjaro you can do that in Kvantum Manager

![image](https://user-images.githubusercontent.com/7688496/143948090-17d02efd-73f9-41b6-b4f8-e1b4ff84f537.png)

**Comment by stephanlachnit** [comment]
Ahhh I see. That is kinda not good. The problem I see is that there is no way to force a specific kvantum theme via command line. Well, you can, but by default it looks just like Fusion and thus without forcing the user to select a theme in kvantum manager this is kinda impossible :/

**Comment by benjamimgois** [comment]
Yeah... not a good spot here. What if we created anothor .desktop file ? The "normal" one would stick to the fusion style, and a new "goverlay-breeze" could force the breeze theme ? Not ideal, but at least the user have an alternative path.

**Comment by stephanlachnit** [comment]
Hm yeah idk. Are you using a default of a specific distro or a custom theme?

In the best case scenario an application should be developed for the largest user base. You can get Breeze on essentially all distros as it is the KDE default, so it would be a good development default in theory.

**Comment by benjamimgois** [comment]
Nope, i'm using the stock Manjaro Breeze-dark. I'll try to improve this situation in the next days. Maybe, i can add a option inside the APP to change the background colors.

**Comment by stephanlachnit** [comment]
> Nope, i'm using the stock Manjaro Breeze-dark. I'll try to improve this situation in the next days. Maybe, i can add a option inside the APP to change the background colors.

What if you developed the gui with Breeze(-dark) instead and make then adjustments so that it also looks good on Fusion / Kvantum? This way more users should get it working properly without additional fixes.

**Comment by benjamimgois** [comment]
> > Nope, i'm using the stock Manjaro Breeze-dark. I'll try to improve this situation in the next days. Maybe, i can add a option inside the APP to change the background colors.
> 
> What if you developed the gui with Breeze(-dark) instead and make then adjustments so that it also looks good on Fusion / Kvantum? This way more users should get it working properly without additional fixes.

I'll keep 0.7 the way it was originally intended, but will focus on Breath theme appearance from now on.

**Comment by stephanlachnit** [comment]
Sounds reasonable, thanks!

**Comment by stephanlachnit** [comment]
Doesn't look too bad! Any ideas how to get dark color for the "page switcher"?

**Comment by benjamimgois** [comment]
> Looks good! Any ideas how to get dark color for the "page switcher"?

The current implementation is on the git version already. I have and idea to fix the issue.... Will make some tests later.

**Comment by luni3359** [comment]
Kind of a late considering the work that has been done, but in response to the very first message but it looks the same on KDE Plasma.

**Comment by benjamimgois** [comment]
Man, i didn't think this could become such a nightmare. I find a way to disable the fusion theme for gtk-desktops. The problem is, the colors are fixed but several controls have diferent proportions and the buttons loose their colors. 

![image](https://user-images.githubusercontent.com/7688496/144653683-14d7a7e6-8bea-4583-b3e7-f93b98e39518.png)

**Comment by cpw** [comment]
Hi. I just tried to update my desktop to latest debian sid, which includes Goverlay 0.7. It looks like this new dependency on breeze is pulling in some portion of the KDE desktop (I don't have KDE otherwise installed, because its a massive bloat), which is going to result in some really derpy libqt applications, sadly, including, it looks like, this one :disappointed:

**Comment by stephanlachnit** [comment]
I patched 0.7 in Debian in Sid with Breeze to make it usable on Gnome (if I can't use the application as the maintainer then that would be kinda bad). Workaround until this is resolved properly.

**Comment by cpw** [comment]
Fair enough, but sadly I've found that libqt applications behave really weirdly when they have that "half a KDE desktop" installed in the past, so I try and avoid it if possible.

**Comment by benjamimgois** [comment]
Sorry guys, lots of personal stuff lately... but i'll be back to fix this as soon as possible.

**Comment by benjamimgois** [comment]
After many tries, indeed switching to breeze is the best workaround. I still prefer the Fusion look, but breeze does the job quiet well. I had to make some small fixes on the UI, Fusion and Breeze have diferences in the components sizes. Could you check if it works on Gnome desktops now ? I tried to test it on fedora, but couldn't figure what package i had to install to got the Breeze style avaiable.

Here's how it looks on the latest git version.
![image](https://user-images.githubusercontent.com/7688496/146209971-ed7ed40b-959d-4326-bb4a-6dbed1b09e27.png)

![image](https://user-images.githubusercontent.com/7688496/146210077-4f3eb710-fff5-4d71-b4cd-ea0247b923f3.png)

**Comment by stephanlachnit** [comment]
I'll check it out later, looks good on the screenshots!

**Comment by stephanlachnit** [comment]
Also looks like that for me 👍🏼

**Comment by alosarjos** [comment]
I just tried to start goverlay afer some time without needing it and found this. I'm guessing now breeze (Which are a bunch of packages and dependencies) is required? Are there plans or have been any testing on trying to get goverlay distributed as a flatpak using the KDE runtime? I'm not an expert but if there is no problem I would love to give it a try.

**Comment by yochananmarqos** [comment]
Looks fine on Manjaro GNOME using QGnomePlatform, `breeze` is not installed.
![Screenshot from 2021-12-17 10-30-24](https://user-images.githubusercontent.com/5437803/146584595-0dd31ff8-f4b7-4c66-b481-c72c65bf78bd.png)

**Comment by benjamimgois** [comment]
> I just tried to start goverlay afer some time without needing it and found this. I'm guessing now breeze (Which are a bunch of packages and dependencies) is required? Are there plans or have been any testing on trying to get goverlay distributed as a flatpak using the KDE runtime? I'm not an expert but if there is no problem I would love to give it a try.

I still have to take a look at flatpak, indeed it would be great if we could create a single package with **mangohud + goverlay**.

**Comment by Devorlon** [comment]
> Looks fine on Manjaro GNOME using QGnomePlatform, `breeze` is not installed. ![Screenshot from 2021-12-17 10-30-24](https://user-images.githubusercontent.com/5437803/146584595-0dd31ff8-f4b7-4c66-b481-c72c65bf78bd.png)

Thanks, installing QGnomePlatform fixed it for me as well.
