### ISSUE TITLE
Mangohud not showing up

### ISSUE THREAD

**Issue by IgorPereira1997** [benjamimgois/goverlay#168]
After 0.7 update, MangoHud does not preview on home screen, so we can't see the changes made.

(https://i.imgur.com/zfsaaSR.png)

**Comment by benjamimgois** [comment]
I made some changes in the latest hours. Could you update and take a look ? 

If it doesn't work, try to run it with `QT_QPA_PLATFORM=xcb mangohud --dlsym goverlay --style fusion`.

**Comment by IgorPereira1997** [comment]
Sure, i'll check it out.

**Comment by IgorPereira1997** [comment]
With the commando you sent, it works with no problem

(https://i.imgur.com/1dNhtn7.png)

**Comment by IgorPereira1997** [comment]
Changed the .desktop EXEC line with your command, and now it works from the launcher also

Contents of .desktop:

[Desktop Entry]
Name=GOverlay
Comment=Graphical UI to help manage Vulkan / OpenGL overlays
*Exec=QT_QPA_PLATFORM=xcb mangohud --dlsym goverlay --style fusion
Icon=goverlay
Terminal=false
Type=Application
Categories=Game;
Keywords=MangoHud;vkBasalt;ReplaySorcery;msi;afterburner;

* = line changed

**Comment by benjamimgois** [comment]
> With the command you sent, it works with no problem.
> 
> (https://i.imgur.com/1dNhtn7.png)

For some reason the correct start script isn't working for some users. How do you installed the app ? on the AUR there's 3 packages `goverlay`, `goverlay-bin` and `goverlay-git`, witch one did you use ?

**Comment by IgorPereira1997** [comment]
I used goverlay-bin to install the app

**Comment by benjamimgois** [comment]
> I used goverlay-bin to install the app

Bingo, i think that might be the problem. The goverlay-bin do not have the correct startup script. That might be affecting lots of users. One last favor, could you remove `goverlay-bin` and install `goverlay-git` ? see if everything work as it should.

**Comment by IgorPereira1997** [comment]
Yeah, that did it, now without any tweaking, it works flawlessly.

(https://i.imgur.com/9fD6Diw.png)

**Comment by IgorPereira1997** [comment]
Btw, thanks for the fast troubleshooting

**Comment by benjamimgois** [comment]
i'll notify the `goverlay-bin` mantainer. Thanks for the help @IgorPereira1997

**Comment by IgorPereira1997** [comment]
No problem, thanks for your awesome app
