### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by JustCauseWhyNot** [benjamimgois/goverlay#17]
If I set a a custom font in `~/.config/MangoHud/MangoHud.conf` with `font_file, and font_file_text`. Then run goverlay & save any changes to the conf file using goverlay. The font variables get overwritten. And there's no support for settings custom fonts in goverlay itself only a pregenerated list of two fonts.

**Comment by benjamimgois** [comment]
Hi @JustCauseWhyNot , goverlay generate a new `mangohud.conf` so any changes that you made by hand will be overwritten. There's no support for custom fonts at the moment. Wich fonts would you like to be avaiable ? I can take a look.

**Comment by JustCauseWhyNot** [comment]
Would it be possible to implement a feature that enables setting a custom font that's already installed on your system?
