### ISSUE TITLE
Build fails on Ubuntu 21.10

### ISSUE THREAD

**Issue by Ahmed-E-86** [benjamimgois/goverlay#170]
I tried to follow the installation from source on Ubuntu 21.10, but after executing make, I get this error:

```
lazbuild -B goverlay.lpi --bm=Release 
make: lazbuild: No such file or directory
make: *** [Makefile:9: goverlay] Error 127
```

**Comment by Ahmed-E-86** [comment]
The application itself runs without installing, but it looks like this:

![Screenshot from 2021-11-30 17-38-19](https://user-images.githubusercontent.com/29783425/144078519-1e477e68-314e-43e8-9b03-90f1165f53d0.png)

**Comment by benjamimgois** [comment]
Yeah, i'm aware of that problem. Seems that QT apps on Gnome use the light theme by default, even if your system is using the dark variant. Right now the only solution is forcing the yaru-dark on Kvantum-manager. Right now this problem affects all gnome users, but works fine on plasma. I'll work in a fix for 0.7.1

**Comment by Ahmed-E-86** [comment]
Thanks for your reply. What about the build error? Do you know what causes it?

**Comment by benjamimgois** [comment]
> Thanks for your reply. What about the build error? Do you know what causes it?

Try to compile just with a make command:

![image](https://user-images.githubusercontent.com/7688496/144096961-a23afaf7-93ab-42e2-850e-4c04cdf44437.png)

**Comment by Ahmed-E-86** [comment]
I already did that, and I got the error I mentioned before.

**Comment by benjamimgois** [comment]
I'll take a look. Not sure yet

**Comment by benjamimgois** [comment]
@Ahmed-E-86 sorry for taking so long, i wish i had more time to dedicate to this project. Unfortunatly i have no idea why this is happening on Ubuntu. I guess this is one of the problems developing for linux, there're so many variations that we can't track down what happens in every diferent distro. Opensuse also has some strange issues that doesn't happen in other distros. I'll mark this post asking for help.

**Comment by stephanlachnit** [comment]
@Ahmed-E-86 can you give me the output of `apt list lcl-utils-2.0`? Looks like you are missing the `lazbuild` executable, which is a required build dependency.

**Comment by stephanlachnit** [comment]
> > @Ahmed-E-86 can you give me the output of `apt list lcl-utils-2.0`?
> 
> ```
> Listing... Done
> lcl-utils-2.0/impish 2.0.12+dfsg-1 amd64
> ```

Jup, so you are missing build dependencies.

> > Looks like you are missing the `lazbuild` executable, which is a required build dependency.
> 
> What is the name of that dependency?

`sudo apt install fpc lcl-2.0 lcl-qt5-2.0 lazarus-src-2.0 libgl-dev` will install everything you need

**Comment by Ahmed-E-86** [comment]
Thanks for your help.

The application works amazing, but there 2 notes:

1- There is a typo in Global Enable's tooltip of vkBasalt.

2- Time is in 24 hours format and there is no option to change it to 12 hours format

I prefer time at this format: `time_format=%l:%M %p`, and it will be nice if it is available as an option.

I would also like to know what is the difference between these three options:

![image](https://user-images.githubusercontent.com/29783425/146441034-14749798-1ec9-438f-9205-ee20bcf15dc9.png)
