### ISSUE TITLE
Cant go past 200fps as fps limit.

### ISSUE THREAD

**Issue by sull324** [benjamimgois/goverlay#172]
i have an 240hz screen and cant set my fps over 200 in the custom setting.Would it be possible to go past 200fps in the custom overlay settings?. Thank you

**Comment by benjamimgois** [comment]
Hi @sull324 , indeed that is a issue. I'll make an update to unlock the custom field to 999fps. But there's already a option for 240fps.

![image](https://user-images.githubusercontent.com/7688496/146548967-6c31a98d-da0c-4e49-b76e-27a6675c0c43.png)

**Comment by sull324** [comment]
thank you for your time.

i was ware of the 240 fpa option i just wanted to test 235 for freesync
testing and purpose.

**Comment by benjamimgois** [comment]
> thank you for your time. i was ware of the 240 fpa option i just wanted to test 235 for freesync testing and purpose.

got it... i will upload a fix to git asap.

**Comment by benjamimgois** [comment]
Just made the fix in a small update. It'll be on the next point release 0.7.2

**Comment by benjamimgois** [comment]
Fixed in 0.8. Thanks for reporting
