### ISSUE TITLE
doesn't work on Pop!_OS 21.10

### ISSUE THREAD

**Issue by cokolwiek555666** [benjamimgois/goverlay#174]
stopped working after upgrade to Pop!_OS 21.10
steam games with "mangohud %command%" not starting
I uninstalled and installed again through Pop!_Shop and nothing changed

**Comment by cokolwiek555666** [comment]
ok I figured it out.
The version of mangohud that Goverlay installs is too old now.
I had to install latest version of mangohud from github.

I have a question, can I somehow install Goveraly to just make mangohud config from GUI?
when I install it normally it brokes my mangohud :(

**Comment by benjamimgois** [comment]
Sorry, i forgot to answer you @cokolwiek555666. Yes, in the end goverlay basicaly creates the mangohud.conf. You can use the latest mangohud that you compile from git with no problems. It would be easier for you to just grab the latest goverlay binarie (tar.xz) and run it from the terminal, no need to suffer with the package manager breaking stuff.

https://github.com/benjamimgois/goverlay/releases/download/0.7.1/goverlay_0_7_1.tar.xz

**Comment by cokolwiek555666** [comment]
@benjamimgois Thanks, I am good now :+1:
