### ISSUE TITLE
[Tumbleweed] can't get libdl.so

### ISSUE THREAD

**Issue by d3vilguard** [benjamimgois/goverlay#175]
Latest Tumbleweed. Installing with **zypper in goverlay**

```
d3vil@openSUSE:~> goverlay
can't get libdl.so

```

**Comment by kevinsmia1939** [comment]
likely duplicate of this https://github.com/benjamimgois/goverlay/issues/156

**Comment by kevinsmia1939** [comment]
I think we can close this too because #156 .

**Comment by benjamimgois** [comment]
Ok, thanks !
