### ISSUE TITLE
Faulty config file causing Steam game crashes

### ISSUE THREAD

**Issue by hombiebearcat** [benjamimgois/goverlay#178]
GOverlay-generated config files contain these two lines, which appear to cause a crash 15-30mins into Steam gameplay:
```
exec=echo #add a line for text space
exec=echo #add a line for text space
```
Removing these lines made the problem go away. [This](https://forum.endeavouros.com/t/mangohud-crashing-steam-in-the-background/20698/13) forum post first made me aware that this was the issue.

**Comment by benjamimgois** [comment]
thanks for reporting it @hombiebearcat , i'll release a fix update for it.

**Comment by benjamimgois** [comment]
Just made a small update, i just removed the "echo" command. Hope it fixes the issue, if it doesn't i'll remove the lines completely. Could you test if it works for you ? It's on the latest git code.

**Comment by hombiebearcat** [comment]
Didn't see it until now - hopefully I'll get the chance to try that out today or at some other point this week

**Comment by hombiebearcat** [comment]
Was able to try it today - seems fine on my end :+1:

**Comment by benjamimgois** [comment]
Great ! it'll land officialy in next release. Thanks for testing !
