### ISSUE TITLE
Provide an icon

### ISSUE THREAD

**Issue by stephanlachnit** [benjamimgois/goverlay#18]
I'm currently looking into packaging this for Debian (and thus Ubuntu and co), and I noticed that there is no real icon for the .desktop file. I think the `goverlay3t256.png` picture would be nice as an icon.

In the best case scenario the icon would be an svg, but if that's not possible a 256x256 or 512x512 png works as well (`goverlay3t256.png` is 256x229, which is problematic).
On a white background (for example when viewing the picture on github), the grey walls are barely visible. It would be awesome if you could make them a little bit bigger for the icon.

It's been quite a while since I used Lazarus, but IIRC it's would be possible to replace the Lazarus default `goverlay.ico` with that as well.

**Comment by benjamimgois** [comment]
will try to work on that @stephanlachnit . Indeed the goverlay3t256.png is used as an icon in the AUR package.

**Comment by benjamimgois** [comment]
@stephanlachnit just made some 128x128, 256x256 and 512x512 icons. Unfortunatly svg will not be possible.


![goverlay-logo-square-128](https://user-images.githubusercontent.com/7688496/80400537-4f485f80-8891-11ea-93e5-61a36b3c5ecf.png)
![goverlay-logo-square-256](https://user-images.githubusercontent.com/7688496/80400551-52dbe680-8891-11ea-9287-3260e62ce025.png)
![goverlay-logo-square-512](https://user-images.githubusercontent.com/7688496/80400552-53747d00-8891-11ea-8e38-f2055e6f075e.png)

**Comment by stephanlachnit** [comment]
![512x512_edited](https://user-images.githubusercontent.com/36662302/80401893-5a18e980-88bd-11ea-9a20-350882b19756.png)

This is what I achieved with a little bit of GIMP magic. I copied the layer, filled the shapes with the grey color and then grew each shape by 2px. Not perfect, but I guess it's good enough for now.

**Comment by benjamimgois** [comment]
Nice work !

**Comment by stephanlachnit** [comment]
> Nice work !

Thanks, I also started Inkscape and tried to vectorize it, but that's still a WIP.
