### ISSUE TITLE
Application wont adapt to screen size

### ISSUE THREAD

**Issue by LuizSerapiao** [benjamimgois/goverlay#18]
I'm using a laptop with a 768p screen. App is to big and wont adapt window for screen size.
Zorin OS 16
GOverlay 0.6.1

**Comment by benjamimgois** [comment]
You are using a very old goverlay version, the app had a major UI change in later versions.

**Comment by LuizSerapiao** [comment]
Im having trouble installing from releases (glibc related problem), is it possible to update the ubuntu ppa?
