### ISSUE TITLE
goverlay has no text in ui

### ISSUE THREAD

**Issue by chriskikker** [benjamimgois/goverlay#181]
i already tried a lot to fix it, ive used the command 'mangohud --dlsym ./goverlay --style fusion' before, it didnt work either, im kinda new to linux so, i appreciate every help, thank you.

![image](https://user-images.githubusercontent.com/75849469/150986785-064e959d-65ca-456d-bbd4-c2a1869ff8fc.png)

**Comment by benjamimgois** [comment]
Hey @chriskikker welcome to the linux world. What distribution are you running ? Is it ubuntu ?

There red dot in the left corner indicates that you're missing mangohud. Mangohud is the program that "draws" the information on the screen. Think of mangohud as **rivatuner statistics server** and goverlay as **Msi afterburner**.

If you're on ubuntu (or any debian based distro). You can install everything via se software center, just install goverlay and it will automatically install mangohud for you. You can also install it from the terminal with simples commands:

```
sudo apt update
sudo apt-get -y install goverlay
```

**Comment by chriskikker** [comment]
> Hey @chriskikker welcome to the linux world. What distribution are you running ? Is it ubuntu ?
> 
> There red dot in the left corner indicates that you're missing mangohud. Mangohud is the program that "draws" the information on the screen. Think of mangohud as **rivatuner statistics server** and goverlay as **Msi afterburner**.
> 
> If you're on ubuntu (or any debian based distro). You can install everything via se software center, just install goverlay and it will automatically install mangohud for you. You can also install it from the terminal with simples commands:
> 
> ```
> sudo apt update
> sudo apt-get -y install goverlay
> ```

heyy, thanks for the fast reply, I had mangohud installed when I put this up. I switched to pop os and just installed it pretty quickly, I don't know what the issue was still.

**Comment by pakro** [comment]
Im having exakt the same issue. I'm using Arch.

Mangohud is installed with the following versions:

lib32-mangohud-git 0.6.6.1.r78.g4943129-1
mangohud-git 0.6.6.1.r78.g4943129-1
