### ISSUE TITLE
"Normal" hint on many windows - is it Goverlay?

### ISSUE THREAD

**Issue by UnclePsymon** [benjamimgois/goverlay#184]
Hi, i have that wied "Normal" hint on many windows. Is this caused by Goverlay? Thanks!
![brave](https://user-images.githubusercontent.com/86851905/151249238-3e80aa02-de7c-4c83-a498-137d083f1ce0.png)
![steam](https://user-images.githubusercontent.com/86851905/151249248-27bd9e4b-33f8-49f5-8e7a-a61154107b6e.png)

**Comment by benjamimgois** [comment]
Nope, it isn't.
