### ISSUE TITLE
White Text on white Background in UI

### ISSUE THREAD

**Issue by pakro** [benjamimgois/goverlay#185]
Hi there,

don't know if this is already a reported problem, but I can't see the text explaining the bells and whistels on the UI in the latest master version because it is basically white on white.

![white_text_und_white_background](https://user-images.githubusercontent.com/8904139/151315257-b3194b0a-94f8-440a-8433-013c5cac0eb2.png)

**Comment by benjamimgois** [comment]
Hey @pakro, i'm experimenting in the latest master. It seems a issue with the latest lazarus. Please, stick to 0.7.1 stable for now.

**Comment by benjamimgois** [comment]
@pakro the latest goverlay default theme is Breeze. Be sure to have it installed in your system.

**Comment by ryaniskira** [comment]
I can confirm this issue, and it remains even with 0.7.1. I do have the Breeze theme installed.

**Comment by helcone** [comment]
Ok so for me installing breeze and goverlay-bin fix the issue on arch what run was.
`yay -S extra/breeze{,-icons,-gtk,-grub} && yay -S "goverlay=0.7.1"`
And I can see again the text.

**Comment by benjamimgois** [comment]
The new release has a dependency warning for systems lacking the breeze package. Thanks for reporting
