### ISSUE TITLE
Installation prevents .bashrc from being sourced

### ISSUE THREAD

**Issue by viseztrance** [benjamimgois/goverlay#186]
Installing goverlay broke my terminal custom prompt.

On my Ubuntu 20.04 installation, it created a `.bash_profile` file with a single line:

```
export MANGOHUD=1
```
Creating that file causes the terminal to source it and skips the existing `.profile`, where `.bashrc` would had normally been sourced.

Strangely enough, it has made a backup of `.profile`, named `.profile_bkp`.

**Comment by benjamimgois** [comment]
I'm so sorry @viseztrance , i think it's part of the old "Global enable" method. I'll track it down for next release.

**Comment by benjamimgois** [comment]
Fixed in 0.8. Thanks for reporting
