### ISSUE TITLE
Request to add the option to set a time limit for the benchmark logging function.

### ISSUE THREAD

**Issue by subanz** [benjamimgois/goverlay#188]
The functionality already seems to exist in MangoHud under the log_duration option, we just need the user interface in GOverlay.

**Comment by benjamimgois** [comment]
Just added the function in latest 0.8. But it seems there's some problems with it. Im my testing sometimes it work and sometimes i don't. Could you try it a report back ?

**Comment by subanz** [comment]
There is one minor issue the hoover text for the Duration input box still says "Autostart logging after X seconds. "0" disable autologging".

Not sure if you meant to replace the auto start logging input box with the duration one or if that is also a bug.

I've done some limited testing of the duration limit and it worked every time so far. I'll let you know if I notice any other issues.

Thank you for all your hard work.

**Comment by benjamimgois** [comment]
Ops... i forgot to update the hover text, will do it asap. Will double check the button aligments.

**Comment by subanz** [comment]
I tested the latest version and everything works very well. 
Both auto start logging and logging duration work, all the buttons are properly aligned.
Thank you.

**Comment by benjamimgois** [comment]
thanks for the feedback @subanz
