### ISSUE TITLE
Add FPS_only flag

### ISSUE THREAD

**Issue by Bitwolfies** [benjamimgois/goverlay#192]
Mangohud has an option to display *just* the fps, no opengl/vullkan, as far as I can tell, this is not an option for the overlay, it would be nice to have for convenience.

**Comment by benjamimgois** [comment]
Implemented in the latest git, wil be avaiable in next release

**Comment by benjamimgois** [comment]
Added in latest 0.8 release

**Comment by Bitwolfies** [comment]
Thanks for the quick response, and the flag is there now! But it still seems to display the milliseconds next to it with no way to disable it, any fix? 
![image](https://user-images.githubusercontent.com/65789901/156048691-72fe71ff-9120-4ce4-941b-37d5396da256.png)

**Comment by benjamimgois** [comment]
@Bitwolfies saddly there's nothing i can do in goverlay, this is the way it's implemented in mangohud. You can open a issue on mangohud, if they make a fix or a new implementation there it'll show up on goverlay.

**Comment by Bitwolfies** [comment]
> @Bitwolfies saddly there's nothing i can do in goverlay, this is the way it's implemented in mangohud. You can open a issue on mangohud, if they make a fix or a new implementation there it'll show up on goverlay.

https://github.com/flightlessmango/MangoHud/issues/674#issuecomment-1045605982

It is possible with some more config lines, sadly cant remember what i used, but its in that thread.

**Comment by benjamimgois** [comment]
> It is possible with some more config lines, sadly cant remember what i used, but its in that thread.

Huummm.... i'll take a look.
