### ISSUE TITLE
crashes from .desktop lacking permission from terminal

### ISSUE THREAD

**Issue by djhnsn** [benjamimgois/goverlay#194]
In manjaro ,from the terminal running goverlay results in env: ‘/usr/lib/goverlay’: Permission denied

running sudo goverlay results in env: ‘/usr/lib/goverlay’: Permission denied

trying to launch from the shortcut, it doesn't open

**Comment by massatt212** [comment]
im having them same problem

**Comment by benjamimgois** [comment]
> In manjaro ,from the terminal running goverlay results in env: ‘/usr/lib/goverlay’: Permission denied
> 
> running sudo goverlay results in env: ‘/usr/lib/goverlay’: Permission denied
> 
> trying to launch from the shortcut, it doesn't open

That is really strange. Do you install it via AUR ?  Please remove the package via pamac and make sure to remove all the traces from the system with:

```
sudo rm /usr/bin/goverlay
sudo rm /usr/lib/goverlay 
sudo rm -r $HOME/.config/goverlay
sudo rm -r $HOME/.config/MangoHud/
sudo rm -r /tmp/goverlay
```

Than install it from scratch with `pamac install goverlay-git`

Let me know the results please.

**Comment by djhnsn** [comment]
> 

That worked, goverlay-bin is what's broken for me.

**Comment by benjamimgois** [comment]
Nice ! it's a different package, it should be updated soon. Thanks for reporting.
