### ISSUE TITLE
goverlay doesnt launch: env: ‘/usr/lib/goverlay’: Permission denied

### ISSUE THREAD

**Issue by TimeFreeze1337** [benjamimgois/goverlay#195]
Running Arch Linux, updated to latest version [AUR] and now goverlay wont open anymore and when i try to launch it from the Terminal i get env: ‘/usr/lib/goverlay’: Permission denied

With the previous version i had no issues.

EDIT: Tried installing the goverlay-git aur version and with that it works. So it seems an issues with the  goverlay-bin version?

**Comment by benjamimgois** [comment]
@TimeFreeze1337 yes, there's a issue in the goverlay-bin. I'll talk to the package mantainer.

**Comment by benjamimgois** [comment]
Fixed in the latest `goverlay-bin`. Thanks for reporting
