### ISSUE TITLE
Check whether MangoHud or vkBasalt are installed

### ISSUE THREAD

**Issue by stephanlachnit** [benjamimgois/goverlay#21]
GOverlay should check whether MangoHud or vkBasalt are installed before allowing to access the windows. I'm doing this since vkBasalt is right now basically impossible to pack for distro use (the Maintainer refuses to add a proper build system), but I still want to pack GOverlay and MangoHud for Debian.

**Comment by benjamimgois** [comment]
Very good point @stephanlachnit i'll try to solve this in the next release (wich should be soon).

**Comment by benjamimgois** [comment]
@stephanlachnit on 0.3.6 i implemented a status message to show if there're dependencies missing. It will not block the access to the panels, but will notify you if something is missing.

**Comment by yochananmarqos** [comment]
I now see the warning "Missing `libMangoHud.so`", yet it is indeed installed to `/usr/lib/mangohud/`.

`goverlay-git` 0.3.6.r1.g8a0d84a-1 
`mangohud` 0.4.1-1
Manjaro GNOME

@stephanlachnit The `vkbasalt` AUR package built fine for me as of 0.3.2.2, take a look at the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vkbasalt).

**Comment by stephanlachnit** [comment]
Yeah the library finding approach only works for some setups with hard coded paths. I think also it's better to look for the Vulkan overlay path instead of the library paths.
This means `/usr/share/vulkan/implicit_layer.d/MangoHud.json` for MangoHud and `/usr/share/vulkan/implicit_layer.d/vkBasalt.json` for vkBasalt.

Here is the problem with the libraries:
- FHS 3.0 system have their libraries in `/usr/lib/libsomething.so`. However, not when Multi-Arch (i. e. 32 bit) is enabled, that behavior isn't defined. `/usr/lib` can be a symlink to `/usr/lib64` _or_ `/usr/lib32` (it's not defined in the FHS).
- Debian based systems don't follow the FHS in that regard because of the Mutli-Arch problems, and libraries go into `/usr/lib/cpu-arch/libsomething.so`, so the current code will definitely not work with Debian based systems.
- Both MangoHud and vkBasalt aren't actually typical "shared libraries", in the sense that they only really used for on application and aren't designed to be linked against. So those shouldn't even be in the libdir, at least when you follow the Debian policy. Instead, they should be in a package specific subfolder. So this means `/usr/libdir/mangohud/libMangoHud.so` and `/usr/libdir/vkbasalt/libvkbasalt.so`. More on this [here](https://github.com/flightlessmango/MangoHud/pull/273) and [here](https://github.com/DadSchoorse/vkBasalt/pull/97).

> @stephanlachnit The vkbasalt AUR package built fine for me as of 0.3.2.2, take a look at the PKGBUILD.

Nothing wrong with the PKGBUILD file^^ Just a little suggestion: use `ninja install` instead of moving the files by hand. Less work needed to maintain it if something changes :)

**Comment by danyeet** [comment]
Getting the warning too even though both mangohud and it's lib32 counterpart is installed.
Vkbasalt works just fine though :D.

**Comment by yochananmarqos** [comment]
@stephanlachnit 

> Nothing wrong with the PKGBUILD file

Actually there's a lot wrong with it, it turns out. Here's [mine](https://github.com/yochananmarqos/pkgbuilds/blob/master/vkbasalt/PKGBUILD) using the latest [commit](https://github.com/DadSchoorse/vkBasalt/commit/7cd22a16120d39e8f7d734dacd5dc8f43a4ffeee) which supposedly adds the option to install to a private directory. However, I had to specify it anyway.

**Comment by stephanlachnit** [comment]
> @stephanlachnit 
> 
> > Nothing wrong with the PKGBUILD file
> 
> Actually there's a lot wrong with it, it turns out. Here's [mine](https://github.com/yochananmarqos/pkgbuilds/blob/master/vkbasalt/PKGBUILD) using the latest [commit](https://github.com/DadSchoorse/vkBasalt/commit/7cd22a16120d39e8f7d734dacd5dc8f43a4ffeee) which supposedly adds the option to install to a private directory. However, I had to specify it anyway.

Yeah I know about that commit it was from me :)

With "nothing wrong" I meant less about if it actually is good style (I don't know much about PKGBUILD files since I'm on Debian), but that the PKGBUILD file isn't the reason for the warning in GOverlay.

**Comment by yochananmarqos** [comment]
> it was from me

Ha, should have known. I didn't even notice it was a PR.

I used the `-Dappend_libdir_vkbasalt=true` Meson flag, but on it's own it doesn't do anything. I had to add `--libdir=lib/vkbasalt` and `--libdir=lib32/vkbasalt` which I think would work regardless of the flag. Am I missing something?

**Comment by stephanlachnit** [comment]
@benjamimgois @yochananmarqos I created a fix in #49.

**Comment by benjamimgois** [comment]
@stephanlachnit Your solution seems to work fine, but the json file that i have in  /usr/share/vulkan/implicit_layer.d is **"MangoHud.x86_64.json"** and not **"MangoHud.json"** so i still got the error message por Mangohud.

**Comment by yochananmarqos** [comment]
@stephanlachnit There are separate arch-specific JSON's with the MangoHUD AUR packages:

```
$ ls /usr/share/vulkan/implicit_layer.d
MangoHud.x86.json  MangoHud.x86_64.json  vkBasalt.json
```

**Comment by stephanlachnit** [comment]
Ahhh yeah I did it for the ld-preload-2 branch of MangoHud. Basically we want to get rid of the separate files in MangoHud, hopefully that lands in the next release.
I guess for now it's maybe a good idea to change it to `MangoHud.x86_64.json` until the next version is released.

**Comment by benjamimgois** [comment]
OK, just push the changes.
