### ISSUE TITLE
Advanced build and install system

### ISSUE THREAD

**Issue by stephanlachnit** [benjamimgois/goverlay#22]
To ease distro packaging GOverlay should provide an automated build and install system.

I personally really like [Meson](https://mesonbuild.com/), since it is super easy to work with, (e.g. compared to make you don't need to define any environment variable for edge cases since the distro build system can do that itself). What do you think? If you're okay with that I can provide a PR with meson support.

**Comment by stephanlachnit** [comment]
Hm okay looks like `lazbuild` isn't really designed to be used outside of Lazarus - there are not options to specify an output dir, which makes it impossible to use with Meson. I guess then a Makefile.

**Comment by benjamimgois** [comment]
@stephanlachnit that would be a great addition. I have no idea to do it, can you help ?

**Comment by stephanlachnit** [comment]
I can write a Makefile
