### ISSUE TITLE
Manjaro - Arch Linux goverlay segmentation fault when starting

### ISSUE THREAD

**Issue by mayakrunal** [benjamimgois/goverlay#24]
Hi,

Trying to run the goverlay with manjaro, however running into segmentation fault issue.  

OS Specs: 
OS: Manjaro Linux x86_64 
Host: Inspiron 7501 
Kernel: 5.15.65-1-MANJARO 
Uptime: 31 mins 
Packages: 1330 (pacman) 
Shell: bash 5.1.16 
Resolution: 1920x1080, 1920x1080 
DE: Plasma 5.25.5 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze [GTK2/3] 
Terminal: dolphin 
CPU: Intel i7-10750H (12) @ 5.000GHz 
GPU: NVIDIA 01:00.0 NVIDIA Corporation TU117M 
GPU: Intel CometLake-H GT2 [UHD Graphics] 
Memory: 4602MiB / 15760MiB 

Installed goverlay using below commands.
`pamac install goverlay-bin`
(version is 0.9.1)

Also tried manually compiling with make command after installing lazarus. Both cases getting following error. 

`/usr/bin/goverlay: line 8: 16800 Segmentation fault      (core dumped) QT_QPA_PLATFORM=xcb mangohud --dlsym /usr/lib/goverlay`

I can confirm that mangohud is working fine with steam and lutris both.

**Comment by mayakrunal** [comment]
FYI tried below as well same issue

`goverlay --style breeze`

**Comment by benjamimgois** [comment]
@mayakrunal could you try the `goverlay-git` package ? We had problems with goverlay-bin in the past.

**Comment by mayakrunal** [comment]
@benjamimgois I tried the `goverlay-git` package as you suggested still got the same issue. I am not sure if it has some compiling issue on my end, attached the install & compile log in the file, please have a look. Not a deal breaker for me, for now i am just directly changing the mangohud conf file to customize the FPS overlay in the game.
[goverlay_log.txt](https://github.com/benjamimgois/goverlay/files/9685781/goverlay_log.txt)

**Comment by benjamimgois** [comment]
Very strange @mayakrunal , your compilation logs are correct. goverlay-git is the package i'm using right now on my manjaro system. I would suggest a clean install. First remove the goverlay packages installed via pamac and try to manually remove the files:

```
sudo rm /usr/lib/goverlay
sudo rm /usr/bin/goverlay
rm  -r $HOME/.config/goverlay
rm  -r /tmp/goverlay
```
Now try to install goverlay-git from pamac again.

**Comment by mayakrunal** [comment]
@benjamimgois Tried the same as you mentioned . Clean up the files and reinstall, Still no luck and same issue. Not sure if it has anything to do with lazarus errors while compiling. 

`Hint: (lazarus) Missing state file of LazOpenGLContext 0.0.1: /usr/lib/lazarus/components/opengl/lib/x86_64-linux/qt5/LazOpenGLContext.compiled
Error: (lazarus) unable to create package output directory "/usr/lib/lazarus/components/opengl/lib/x86_64-linux/qt5" of package "LazOpenGLContext 0.0.1"
Hint: (lazarus) normal output directory of package LazOpenGLContext 0.0.1 is not writable: "/usr/lib/lazarus/components/opengl/lib/x86_64-linux/qt5/"
`
- Since i don't want to clean install my manjaro, i'll leave this as it is.

**Comment by benjamimgois** [comment]
Have you tried the precompiled binaries ? See if it works for you.

https://github.com/benjamimgois/goverlay/releases/download/0.9/goverlay_0_9.tar.xz

Another option is use the Chaotic-AUR, they regularly compile packages from the AUR so you don't have to. Actually it's the best way to use AUR in my opinion. See if it solves the problem for you.

https://aur.chaotic.cx/

**Comment by mayakrunal** [comment]
@benjamimgois it's really strange. 

This is the steps i followed. 

1. Remove all mongohud,lazarus,goverlay packages. 
2. install lazarus
3. Clone the MongoHud and manually build it again. 
4. Clone the goverlay repo. (didn't use the AUR just directly cloned from GIT)
5. Build the goverlay. (Didn't install it just built it)
6. If i run the `./goverlay` command i can start the goverlay. (with paint spam in the terminal & no hud)
![Screenshot_20221001_031143](https://user-images.githubusercontent.com/9257042/193341360-3c0ae603-8d36-424c-b612-973785652a0d.png)
7. if i run the `./start_goverlay.sh` or directly `mangohud ./goverlay` it gives me segmentation fault error. 
8. The only thing i can think of is that there is some issue with mangohud it self. since i can start goverlay UI but the error comes as soon as add the mangohud command.

**Comment by mayakrunal** [comment]
As for mongohud i initially installed the community package, and then build it manually as well, both gave me error, Oh FYI, pre-compiled package same issue. can run the goverlay directly but gives error with mangohud.

**Comment by mayakrunal** [comment]
Raised the issue on MongoHud as well. 

https://github.com/flightlessmango/MangoHud/issues/842

**Comment by mayakrunal** [comment]
This is from goverlay source code. 
`#!/bin/sh
# This script will launch the compiled goverlay binary the correct way
#
# QT_QPA_PLATFORM=xcb will force the application to run in x11 mode, so it works on wayland desktops.
# mangohud --dlsym will force the mangohud display on the spinning cube on goverlay.
# Executing this script with --style <style> one can choose different themes.

export QT_QPA_PLATFORM=xcb
mangohud --dlsym @libexecdir@/goverlay $@`
https://github.com/benjamimgois/goverlay/blob/master/data/goverlay.sh.in

**Comment by mayakrunal** [comment]
clean-installed manjaro. working fine now. Something must be wrong with my previous setup, couldn't track down.

**Comment by benjamimgois** [comment]
Good to know. Sometimes it's very hard to track the specific issue. Thanks for the feedback
