### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Tribix** [benjamimgois/goverlay#24]
hello. i couldn't build goverlay.when i write this "lazbuild -B goverlay.lpi" to terminal,this showed up.can you help me ?

tribix@Tribix:~/goverlay$ lazbuild -B goverlay.lpi
Hint: (lazarus) [RunTool] /usr/bin/fpc "-iWTOTP"
Hint: (lazarus) [RunTool] /usr/bin/fpc "-va" "compilertest.pas"
Hint: (lazarus) [RunTool] /usr/bin/fpc "-iWTOTP" "-Px86_64" "-Tlinux"
Hint: (lazarus) [RunTool] /usr/bin/fpc "-va" "-Px86_64" "-Tlinux" "compilertest.pas"
Info: (lazarus) Execute Title="Derleme Projesi, Hedef: goverlay"
Info: (lazarus) Working Directory="/home/tribix/goverlay/"
Info: (lazarus) Executable="/usr/bin/fpc"
Info: (lazarus) Param[0]="-B"
Info: (lazarus) Param[1]="-MObjFPC"
Info: (lazarus) Param[2]="-Scghi"
Info: (lazarus) Param[3]="-Cg"
Info: (lazarus) Param[4]="-O1"
Info: (lazarus) Param[5]="-g"
Info: (lazarus) Param[6]="-gl"
Info: (lazarus) Param[7]="-l"
Info: (lazarus) Param[8]="-vewnhibq"
Info: (lazarus) Param[9]="-Fi/home/tribix/goverlay/lib/x86_64-linux"
Info: (lazarus) Param[10]="-Fu/usr/lib/lazarus/1.8.2/lcl/units/x86_64-linux/gtk2"
Info: (lazarus) Param[11]="-Fu/usr/lib/lazarus/1.8.2/lcl/units/x86_64-linux"
Info: (lazarus) Param[12]="-Fu/usr/lib/lazarus/1.8.2/components/lazutils/lib/x86_64-linux"
Info: (lazarus) Param[13]="-Fu/usr/lib/lazarus/1.8.2/packager/units/x86_64-linux"
Info: (lazarus) Param[14]="-Fu/home/tribix/goverlay/"
Info: (lazarus) Param[15]="-FU/home/tribix/goverlay/lib/x86_64-linux/"
Info: (lazarus) Param[16]="-dLCL"
Info: (lazarus) Param[17]="-dLCLgtk2"
Info: (lazarus) Param[18]="goverlay.lpr"
Hint: (11030) Start of reading config file /etc/fpc.cfg
Hint: (11031) End of reading config file /etc/fpc.cfg
Free Pascal Compiler version 3.0.4+dfsg-18ubuntu2 [2018/08/29] for x86_64
Copyright (c) 1993-2017 by Florian Klaempfl and others
(1002) Target OS: Linux for x86-64
(3104) Compiling goverlay.lpr
Fatal: (10022) Can't find unit FastHTMLParser used by Clipbrd
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
Error: (lazarus) Derleme Projesi, Hedef: goverlay: stopped with exit code 256
Error: (lazbuild) failed compiling of project /home/tribix/goverlay/goverlay.lpi

**Comment by benjamimgois** [comment]
@Tribix i think this is the same problem related on #4 .

> The Lazarus base directory needs to be passed:
> 
> `lazbuild --lazarusdir=/usr/lib/lazarus -B goverlay.lpi`
