### ISSUE TITLE
wrong tag for 0.3.2?

### ISSUE THREAD

**Issue by stephanlachnit** [benjamimgois/goverlay#25]
Just a quick question, the tag for 0.3.2 is at 03bcfc90fcbf84310857e1feca903e932826138c, but the commit with the release message is 35098d643dc27b398c02a0f48fb55c9d79c07af0 (one after that). Is this intended?
I am asking since I need to fetch the source tarball from github for the Debian package.

**Comment by benjamimgois** [comment]
Stephan, it's not. The commit 03bcfc90fcbf84310857e1feca903e932826138c should still be 0.3.1. //i don't know what happen to be honest

**Comment by stephanlachnit** [comment]
```sh
git tag -d 0.3.2
git tag 0.3.2 35098d643dc27b398c02a0f48fb55c9d79c07af0
git push origin -f 0.3.2
```
should fix it, Github should be able to transition the updated tag automatically.

**Comment by benjamimgois** [comment]
Just did... see if it's fixed

**Comment by stephanlachnit** [comment]
Nice, it worked.

**Comment by stephanlachnit** [comment]
I think the tag is wrong again: https://github.com/benjamimgois/goverlay/tree/0.3.3

**Comment by benjamimgois** [comment]
This is a very strange problem.... i just repeat that process, see if it works.

**Comment by stephanlachnit** [comment]
> This is a very strange problem.... i just repeat that process, see if it works.

I think you just pushed 0.3.3 to the same tag, you need to take the ID from the at 0.3.3: https://github.com/benjamimgois/goverlay/commit/0a854f3f24436bc62120bb026c55e06a7f027c5d (the long thing in the url)

Which means:
```sh
git tag -d 0.3.3
git tag 0.3.3 0a854f3f24436bc62120bb026c55e06a7f027c5d
git push origin -f 0.3.3
```

How did you create the tag in the first place? I do it usually by running `git log`, copying the commit ID and then run `git tag <version> <copied_commit_id>`.

**Comment by benjamimgois** [comment]
OK, just did the process again. I usually just upload the files manually via the web browser and type the new tag version. Is it wrong ? Maybe i need some basic git classes. Will take a look at it

**Comment by stephanlachnit** [comment]
> OK, just did the process again. I usually just upload the files manually via the web browser and type the new tag version. Is it wrong ? Maybe i need some basic git classes. Will take a look at it

I wouldn't say it's the wrong approach, but apparently something is going wrong when doing it. Anyway, the tag is correct now. Maybe do it next time just via the command line :)

**Comment by stephanlachnit** [comment]
@benjamimgois 0.3.4 has a wrong tag again^^
See https://github.com/benjamimgois/goverlay/tree/0.3.4, I suppose it should be at https://github.com/benjamimgois/goverlay/commit/acb88626a6b083981ab4f313d9e25f9ad6abdfd3.

```sh
git tag -d 0.3.4
git tag 0.3.4 acb88626a6b083981ab4f313d9e25f9ad6abdfd3
git push origin -f 0.3.4
```

**Comment by benjamimgois** [comment]
@stephanlachnit this time i upload the changes via CLI, i did:

`git commit -a`
`git push origin master`

What am i doing wrong ?

**Comment by stephanlachnit** [comment]
How do you create the tags? The commits are fine, just the tags are somehow messed up.

**Comment by benjamimgois** [comment]
Humm.... just now i realize i didn't create the tag for 0.3.4. When i uploaded the code from the browser i just typed the new tag version on the UI. I've never done it from the CLI.... if i type "git tag" this is what i got... how do i fix this ?

![image](https://user-images.githubusercontent.com/7688496/85229357-9fd6c780-b3bf-11ea-83b8-773245e1b930.png)

**Comment by benjamimgois** [comment]
I made a small new release and think that now i got it right.... please, check if it's correct.

**Comment by stephanlachnit** [comment]
> Humm.... just now i realize i didn't create the tag for 0.3.4. When i uploaded the code from the browser i just typed the new tag version on the UI. I've never done it from the CLI.... if i type "git tag" this is what i got... how do i fix this ?

That probably is the problem. It's best to create a tag using the CLI. Creating a tag works like this
```
git tag <version> <commit_id>
```
Every commit has an ID, no matter if you upload it from the browser or the CLI. When you upload code from the browser, it doesn't automatically just update it in the CLI, that's probably why the 0.3.4 tag is missing then you typed `git tag`. First, you need to fetch from the remote like this:
```sh
git fetch # grab info from the remote
git pull --ff # combine local and remote code
```
After this, when running
```
git log
```
You should see something like this
```
$ git log
commit 2251c544cdd33922b12fac2a0decc9835bbe644d (HEAD -> master, origin/master)
Author: benjamimgois <benjamim.gois@gmail.com>
Date:   Sun Jun 21 21:32:10 2020 -0300

    0.3.5
    
    Removed checkbox from CPU / GPU name
    Made media data combobox read only

commit 01d0de11417a1bb5b71e94cb49a7ee95508cd17e
Author: benjamimgois <benjamim.gois@gmail.com>
Date:   Sat Jun 20 21:02:25 2020 -0300

    Updated install instructions
    
    Add reference to chaotic-aur
    Add debian / ubuntu instalation
```
As you can see, every commit has an ID, for the 0.3.5 commit it's 2251c544cdd33922b12fac2a0decc9835bbe644d (GitHub automatically shortens and hyperlinks these). When you want to make a release based on the code of a specific commit, you do it like this:
```
git tag 0.3.5 2251c544cdd33922b12fac2a0decc9835bbe644d
```
You now created the tag locally, now it needs to be pushed:
```
git push origin 0.3.5
```
Now this is how it would work if there wouldn't be a `0.3.5` tag already on Github, but there is already one, so you need to delete the old tags and force push them:
```
git tag --delete 0.3.4 # delete the old 0.3.4 tag
git tag 0.3.4 acb88626a6b083981ab4f313d9e25f9ad6abdfd3 # create new 0.3.4 tag
git push origin -f 0.3.4 # force push new 0.3.4 tag to GitHub
git tag --delete 0.3.5 # delete the old 0.3.5 tag
git tag 0.3.5 2251c544cdd33922b12fac2a0decc9835bbe644d # create new 0.3.5 tag
git push origin -f 0.3.5 # force push the new 0.3.5 tag to GitHub
```
> I made a small new release and think that now i got it right.... please, check if it's correct.

There both on the wrong commit, you can check it by browsing them on GitHub (or via `git log`):
![0 3 4](https://user-images.githubusercontent.com/36662302/85263126-02d36780-b46f-11ea-8b2a-c15c51422fba.png)
![0 3 5](https://user-images.githubusercontent.com/36662302/85263130-036bfe00-b46f-11ea-9ab4-50705da53d44.png)

**Comment by benjamimgois** [comment]
Man, i have no words to thank you enough for this lecture. I just made the changes...

**Comment by stephanlachnit** [comment]
> Man, i have no words to thank you enough for this lecture. I just made the changes...

No problem :) And it worked, thanks!

**Comment by stephanlachnit** [comment]
The 0.3.6 tag is broken again: https://github.com/benjamimgois/goverlay/commits/0.3.6

**Comment by benjamimgois** [comment]
Just deleted the old 0.3.6 tag and made a:
 
`git tag 0.3.6 8a0d84aeaa0d2d557545705e16561df0db61eca1   `                                                   
`git push origin -f 0.3.6      `     

Is it right ?

**Comment by stephanlachnit** [comment]
Yes!
