### ISSUE TITLE
Replay sorcery always running on startup

### ISSUE THREAD

**Issue by shigutso** [benjamimgois/goverlay#25]
I disabled replay-sorcery from running at startup, using my normal user or root, but it is still running on boot and using 30% of my CPU
How can I fix this?
I want to run it on demand, not always

Distro: Manjaro 22.0
Goverlay version: 0.9-1 (package goverlay-bin from AUR repository)

Thanks

**Comment by benjamimgois** [comment]
Hi @shigutso sorry for that. When you global enable replay sorcery it creates a file inside `$HOME/.config/autostart/replay.desktop`. To fix it, simply remove that file with:

`rm $HOME/.config/autostart/replay.desktop`

Think i'll remove the global enable for replaysorcery in next release. Thanks for pointing the issue.

**Comment by shigutso** [comment]
Sorry for the late reply
Thanks, it worked!
