### ISSUE TITLE
vkBasalt settings

### ISSUE THREAD

**Issue by the-cave-dweller** [benjamimgois/goverlay#27]
Hello, I'm just curious to know if this is the normal behaviour, after saving my basalt shader config, restarting the application makes me have to setup the active effects tab completely again, I'm using the git version, but I'm assuming it should remember or recognize them from the config file at startup

**Comment by benjamimgois** [comment]
Hey @the-cave-dweller , sadly that's the actual behavior.

**Comment by pkejval** [comment]
Hi @benjamimgois , why is that? Is that any sort of bug or intended behaviour?

**Comment by benjamimgois** [comment]
Actually i couldn't make it work the last time i tried, and hasn't go back to it yet. It's in the todo list

**Comment by pkejval** [comment]
@benjamimgois OK, thanks for answer. I was curious if it's my fault or not.

@the-cave-dweller  I actually found manual workaround. Just set desired shaders settings in ~/.config/vkBasalt/vkBasalt.conf

Find line "effects = cas" and append effects/Reshade delimited by semicolon :
like this "effects = cas:smaa:Denoise"

and you can append  "enableOnLaunch = True" to apply effects after starting the game.

**Comment by the-cave-dweller** [comment]
Oh,  thanks 😄,  I'll try, sorry to both, I just read the page, I guess I also should close the issue since its on the future plans ✌️
