### ISSUE TITLE
crtbeginS.o and crtendS.o not found during build

### ISSUE THREAD

**Issue by yochananmarqos** [benjamimgois/goverlay#28]
It appears you may need to add `usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/` to your project as it can't find it.

References:
[Lazarus FAQ](https://wiki.lazarus.freepascal.org/Lazarus_Faq#I_receive_a_warning_during_the_linking_that_states:_Warning:_.22crtbeginS.o.22_.28or_.22crtendS.o.22.29_not_found)
[Lazarus forum
](https://forum.lazarus.freepascal.org/index.php?topic=34288.0)
```
(9022) Compiling resource /home/yochanan/Documents/AUR/goverlay-git/src/goverlay/lib/x86_64-linux/goverlay.or
(9015) Linking /home/yochanan/Documents/AUR/goverlay-git/src/goverlay/goverlay
/home/yochanan/Documents/AUR/goverlay-git/src/goverlay/goverlay.lpr(26,1) Warning: (9034) "crtbeginS.o" not found, this will probably cause a linking failure
/home/yochanan/Documents/AUR/goverlay-git/src/goverlay/goverlay.lpr(26,1) Warning: (9034) "crtendS.o" not found, this will probably cause a linking failure
/usr/sbin/ld: warning: /home/yochanan/Documents/AUR/goverlay-git/src/goverlay/link.res contains output sections; did you forget -T?
```

[Full build log](https://pastebin.com/3JLLkArG)

**Comment by benjamimgois** [comment]
Nice catch ! just added <Libraries Value="/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/"/> to goverlay.lpi. The build r6 is already fixed. Thanks !

**Comment by yochananmarqos** [comment]
Would you believe right after I finally got around to posting this issue, `gcc` updated from 9.30 to 10. 1.0. Can you add `/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/` as well?

**Comment by benjamimgois** [comment]
> Would you believe right after I finally got around to posting this issue, `gcc` updated from 9.30 to 10. 1.0? Can you add `/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/` as well?

Like a friend of mine use to say.... Murphy never sleeps my friend :) . I just added the new path on R7 build.
