### ISSUE TITLE
TAA Implementation

### ISSUE THREAD

**Issue by the-cave-dweller** [benjamimgois/goverlay#29]
Hello, I actually also asked about this on the vkbasalt github, but I was wondering if this TAA implementation for reshade should theoretically work on vkbasalt, sorry if this is not quite related, but it looks quite promising and I really have the doubt.

[https://github.com/JakobPCoder/ReshadeTFAA](url)
[https://github.com/JakobPCoder/ReshadeMotionEstimation](url)

If so, is there a way for it to be selected?, I never configured basalt outside of goverlay before, so I'm not really sure if external effect files can also be implemented.

**Comment by benjamimgois** [comment]
Hi @the-cave-dweller , this is actually a very interesting reshade implementation. I just give it a try, but couldn't make it work. Vkbasalt github is the best place to ask for support. But basically you have to copy the .fx and .fxh files to the `/home/$USER/.local/share/reshade/Shaders/` folder and add the configurations in the vkbasalt.conf file inside `/home$USER/.config/vkBasalt/`

I'll attach the file i used in my tests, if we can make it work i might add it to Goverlay UI.

[vkBasalt.conf.zip](https://github.com/benjamimgois/goverlay/files/9995205/vkBasalt.conf.zip)

**Comment by the-cave-dweller** [comment]
Thanks for such a quick response, I just noticed, what a shame it failed to run atm  :,(, it looks extremely promising, I would try installing it on actual reshade, but the home shortcut is not working on it in my lxqt, thanks for your time =).
