### ISSUE TITLE
Goverlay not launching because of a spdlog error

### ISSUE THREAD

**Issue by linuxtoons** [benjamimgois/goverlay#31]
Trying to launch Goverlay on my Arch Linux system via the `goverlay-bin` package from the AUR. Couldn't get GOverlay to launch so I tried via the terminal and  and I get this error code:

`/usr/lib/goverlay: error while loading shared libraries: libspdlog.so.1: cannot open shared object file: No such file or directory`

I checked to make sure I have the `spdlog` package and its installed and up to date. The one last thing I tried was checking the other goverlay AUR builds and still reproduces the same error.

![Screenshot_20221115_013607](https://user-images.githubusercontent.com/118260621/201884411-439fb696-80d2-4adb-8a78-86a26e56939d.png)

**Comment by m2thay** [comment]
Same issue here, also on Arch, rebuilt with the AUR .git package.

**Comment by benjamimgois** [comment]
Remove mangohud and rebuild it from the AUR. I also had this problem

**Comment by m2thay** [comment]
> Remove mangohud and rebuild it from the AUR. I also had this problem

This worked, thank you for the swift reply.
