### ISSUE TITLE
GOverlay UI error on Linux Mint

### ISSUE THREAD

**Issue by thecursehunter** [benjamimgois/goverlay#32]
I was able to get GOverlay working on Mint after following this instruction: 
"To confirm I did the following on Ubuntu 22.04.

Installed libqt5pas from here - https://github.com/davidbannon/libqt5pas/releases/tag/v1.2.10

Then installed GOverlay

sudo apt-get install goverlay

Then installed MangoHUD from scratch.

git clone --recurse-submodules https://github.com/flightlessmango/MangoHud.git
cd MangoHud
./build.sh build
./build.sh install

Once this was done, GOverlay launched correctly."
However, it looks like this:
![Screenshot from 2022-11-21 11-59-13](https://user-images.githubusercontent.com/73272262/203081061-f0757963-894b-48ed-87c1-137216c53f3f.png)

**Comment by benjamimgois** [comment]
Try the latest 0.9, there're some fixes for the wrong colors.

**Comment by thecursehunter** [comment]
> Try the latest 0.9, there're some fixes for the wrong colors.

where can I get it? 
I installed this version of GOverlay through the repo

**Comment by benjamimgois** [comment]
> > Try the latest 0.9, there're some fixes for the wrong colors.
> 
> where can I get it? I installed this version of GOverlay through the repo

You can [download](https://github.com/benjamimgois/goverlay/releases/download/0.9/goverlay_0_9.tar.xz) the binary from the github. It might take some time for the latest release got into debian/ubuntu repositories.

https://github.com/benjamimgois/goverlay#tarball

**Comment by thecursehunter** [comment]
> > > Try the latest 0.9, there're some fixes for the wrong colors.
> > 
> > 
> > where can I get it? I installed this version of GOverlay through the repo
> 
> You can [download](https://github.com/benjamimgois/goverlay/releases/download/0.9/goverlay_0_9.tar.xz) the binary from the github. It might take some time for the latest release got into debian/ubuntu repositories.
> 
> https://github.com/benjamimgois/goverlay#tarball
![Screenshot from 2022-11-21 21-53-10](https://user-images.githubusercontent.com/73272262/203085587-7fa9789e-43d9-41d1-9442-9c28b6faf2ed.png)
I got this error

**Comment by benjamimgois** [comment]
Try to make the script executable with:

`chmod +x ./start_goverlay.sh`

then, execute it with

`./start_goverlay.sh`

**Comment by thecursehunter** [comment]
> Try to make the script executable with:
> 
> `chmod +x ./start_goverlay.sh`
> 
> then, execute it with
> 
> `./start_goverlay.sh`

Thanks for your help!
Final question before closing, how can I create a appliacation shortcut for this .sh file?

**Comment by benjamimgois** [comment]
You just need to create a text file with the following commands:

sudo nano /usr/share/applications/goverlay.desktop

```
[Desktop Entry]
Name=GOverlay
Comment=Graphical UI to help manage Vulkan / OpenGL overlays
Exec=$HOME/downloads/start_goverlay.sh
Icon=goverlay
Terminal=false
Type=Application
Categories=Game;
Keywords=MangoHud;vkBasalt;ReplaySorcery;msi;afterburner;
```

Just replace the Exec= part with the path where you downloaded goverlay files.

You actually give me an idea, i'll update the script to autocreate the shortcut for the user. Thanks :)

**Comment by thecursehunter** [comment]
> You just need to create a text file with the following commands:
> 
> sudo nano /usr/share/applications/goverlay.desktop
> 
> ```
> [Desktop Entry]
> Name=GOverlay
> Comment=Graphical UI to help manage Vulkan / OpenGL overlays
> Exec=$HOME/downloads/start_goverlay.sh
> Icon=goverlay
> Terminal=false
> Type=Application
> Categories=Game;
> Keywords=MangoHud;vkBasalt;ReplaySorcery;msi;afterburner;
> ```
> 
> Just replace the Exec= part with the path where you downloaded goverlay files.
> 
> You actually give me an idea, i'll update the script to autocreate the shortcut for the user. Thanks :)

No problem
Thank you very much for your super responsive support!!!
