### ISSUE TITLE
How do I go about installing more post-processing shaders to GOverlay/vkBasalt?

### ISSUE THREAD

**Issue by GottaSlay** [benjamimgois/goverlay#34]
[https://github.com/crosire/reshade-shaders/tree/master/Shaders](url) has a bunch of post-processing shaders that I'd like to fiddle around with using GOverlay but I don't know how to go about installing those shaders.

Currently the GUI has options for CAS, FXAA, SMAA, DEBAND and LUT.

**Comment by benjamimgois** [comment]
It's not avaiable right now... it's in my future plans

**Comment by GottaSlay** [comment]
Good to hear!
