### ISSUE TITLE
No HiDPI scaling support?

### ISSUE THREAD

**Issue by jastx-jasmint** [benjamimgois/goverlay#36]
Hi, sorry if this has already been written about somewhere but I haven't been able to find anything - SearX shows that there is a closed issue related to this but the URL is invalid, and it doesn't show up in the issues list (https://github.com/benjamimgois/goverlay/issues/169).

I use KDE Plasma on Garuda Linux with 175% global scaling since that is the only way to not squint at everything on a 4K 15" screen or have everything massive, and goverlay does not conform to this scaling. Thankfully KDE has a desktop zoom i can use so i don't have to break my eyes and neck to look at goverlay, but it would be nice if there were a way to adjust the programs scale.

Here is a screenshot. As you can see, goverlay is teeny tiny compared to everything else.
![Screenshot_63](https://user-images.githubusercontent.com/67564867/207008531-c804ee66-3b38-4e08-aba6-c4af541c7a42.png)

Is this an issue of unsupported fractional scaling? I know that apps like Lutris don't support fractional scaling so I'm stuck with using them as they are. Also, unlike the 'MangoHud is tiny' issue, my MangoHud shows up fine - I would just like to be able to make the window bigger and be able to read comfortably :)
![image](https://user-images.githubusercontent.com/67564867/207009362-a1ec81c1-3124-4563-bcbb-552c67fe2fc6.png)

If any additional details are needed, please let me know and I'll provide them asap. ^^
I got goverlay from the Chaotic AUR and am using the 0.9.1 beta.

**Comment by benjamimgois** [comment]
Hi @jastx-jasmint , this is an old Lazarys problem. I already reported the issue, but it still unfixed.

https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/39610

In the latest git code i disabled the LCL scale and tried to use a qt to scale the GUI, but still no luck.

**Comment by jastx-jasmint** [comment]
Ohh dang, alright no worries :) thankfully I have the zoom thing so it won't be too much of a problem in the meantime.
I find it quite interesting how in the thread you linked, the improper scaling support resulted in words and elements smooshed together, even though the window size itself seems to be nicely scaled. o_o

**Comment by benjamimgois** [comment]
@jastx-jasmint i'm working in a temporary fix for this. It actually worked in my test systems, could you try it and see if it works for your ? Just extract the zip file and execute it in a terminal with 

`QT_QPA_PLATFORM=xcb mangohud --dlsym ./goverlay`


[goverlay_test.zip](https://github.com/benjamimgois/goverlay/files/10263682/goverlay_test.zip)

**Comment by jastx-jasmint** [comment]
Hi, sorry for the late response! I haven't checked Github in a while ^^;
This works great! So much better than before - now I won't have to squint anymore!
Here's a screenshot of how it looks. The text looks normal compared to the mouse cursor now.
![image](https://user-images.githubusercontent.com/67564867/212313959-4f3f0b38-921c-492f-a802-aff5eb6b6329.png)

The vkBasalt text may be a bit on the smaller side for some, but I think it's readable.
![image](https://user-images.githubusercontent.com/67564867/212314029-052758db-2afb-4ca0-80d6-40e74087c4af.png)

**Comment by benjamimgois** [comment]
> The vkBasalt text may be a bit on the smaller side for some, but I think it's readable.

Will add it to the todo list

**Comment by jastx-jasmint** [comment]
Sorry for the late update! I forgot that I made this issue.
HiDPI scaling works now. Thanks for the awesome work benjamimgois!
