### ISSUE TITLE
(Feature Request) Change Mango HUD position 

### ISSUE THREAD

**Issue by jatin-cbs** [benjamimgois/goverlay#36]
Just a feature request as its one of the most common HUD features. GOverlay can make it easier to change position from default top left. Thanks for the amazing work :)

**Comment by benjamimgois** [comment]
@jatin-cbs it's already implemented. There are 4 squares on the center image where you can select the HUD position.

![gov_spots](https://user-images.githubusercontent.com/7688496/85213445-cf8cbd80-b334-11ea-9365-6d82847e6155.png)

**Comment by jatin-cbs** [comment]
but mine just shows circles which i just click nothing happens

**Comment by jatin-cbs** [comment]
Ok its fixed after update
