### ISSUE TITLE
Screenshots / Readme

### ISSUE THREAD

**Issue by stephanlachnit** [benjamimgois/goverlay#40]
@benjamimgois just a little heads up: In this commit (https://github.com/benjamimgois/goverlay/commit/2251c544cdd33922b12fac2a0decc9835bbe644d) you reverted the changes to the readme from those two commits: https://github.com/benjamimgois/goverlay/commit/01d0de11417a1bb5b71e94cb49a7ee95508cd17e, https://github.com/benjamimgois/goverlay/commit/acb88626a6b083981ab4f313d9e25f9ad6abdfd3

Also, when you update the links to the screenshots, can you also update them here:
https://github.com/benjamimgois/goverlay/blob/2a27eeb556e966c9ab48adaed4e71cc855d1bdb6/data/goverlay.metainfo.xml#L18-L27

**Comment by benjamimgois** [comment]
I just notice it now @stephanlachnit. Already remade the changes and update the screenshot on the xml file.
