### ISSUE TITLE
FPS only mode is broken.

### ISSUE THREAD

**Issue by Bitwolfies** [benjamimgois/goverlay#41]
Doesn't seem to be a mangohud issue as it was working fine till I tried changing  the setting back goverlay, makes it look like this (yes even in widescreen)
![Screenshot_20230118_171635](https://user-images.githubusercontent.com/65789901/213332813-486e04cf-6e3c-455d-ba96-3f50958fc71f.png)
Using goverlay-bin from aur and git builds of mangohud also from aur.

**Comment by Calinou** [comment]
@Bitwolfies Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:

**Comment by Bitwolfies** [comment]
Unfortunately not really, I had closed this too fast since I thought it was user issue, you just reminded me of it.

I think it has something to do with swapping between horizontal and vertical mode, the program gets confused and breaks the config. Only solution is to just delete and save a new one.
