### ISSUE TITLE
The repository 'https://mentors.debian.net/debian sid Release' does not have a Release file.

### ISSUE THREAD

**Issue by werymanen** [benjamimgois/goverlay#41]
I am on Ubuntu, so I did what the installation guide said to do (append a line of text to /etc/apt/sources.list), do sudo apt update, but there I got an error saying: ``` E: The repository 'https://mentors.debian.net/debian sid Release' does not have a Release file. ```

What should I do?

**Comment by werymanen** [comment]
I looked around for a bit and found more ways and lines to get mentors.debian.net to work, and neither of them worked, might be a temporary thing at them, still not sure.

**Comment by benjamimgois** [comment]
I'm already checking what's happening to the repository @werymanen , thanks for reporting.

**Comment by werymanen** [comment]
You're welcome 🙂

**Comment by benjamimgois** [comment]
Had to remove the repository from documentation until it get sorted out
