### ISSUE TITLE
Display anomalies under global item scaling

### ISSUE THREAD

**Issue by PTALTS-LK** [benjamimgois/goverlay#43]
I have a 2560*1600 high resolution screen.
So I had to use global item scaling to make UI items easy to see.（150%）
But Goverlay's UI doesn't seem to work perfectly in this case, and the text of the various options overlaps.
I use the KDE plasma desktop environment
![2023-01-27_22-03](https://user-images.githubusercontent.com/62936489/215105669-082b2a7d-bf55-4f89-9155-e21a4d4809f4.png)
![2023-01-27_22-03_1](https://user-images.githubusercontent.com/62936489/215105684-81017edb-79be-4dfe-996e-902107b4d48d.png)
![2023-01-27_22-05](https://user-images.githubusercontent.com/62936489/215105948-8afa5c4a-827c-4f15-993f-6015c3f12263.png)
![2023-01-27_22-05_1](https://user-images.githubusercontent.com/62936489/215105962-2662c6ff-218b-42b7-87d1-495eb6cf5393.png)

**Comment by benjamimgois** [comment]
Hi @PCX-LK , i have being fighting with this scalling issue for some time. In the binary version of the latest release there's a fix that worked for some users. Could you try it ?

https://github.com/benjamimgois/goverlay/releases/download/0.9.1/goverlay_0_9_1.tar.xz

**Comment by PTALTS-LK** [comment]
> **[benjamimgois](/benjamimgois) ** commented

The problem is solved.
It worked.

**Comment by PTALTS-LK** [comment]
![image](https://user-images.githubusercontent.com/62936489/215117436-d155664b-aac2-4e71-8b6c-3ae4b2e8f31a.png)

**Comment by benjamimgois** [comment]
i'll try to implement it in the AUR package. Thanks for the feedback
