### ISSUE TITLE
Doesn't scale well on HiDPI displays

### ISSUE THREAD

**Issue by MetaDark** [benjamimgois/goverlay#44]
With 96 DPI, the GUI is rendered as expected, but it's too small on a 4k screen:

```xrandr --output DP-2 --mode 3840x2160 --dpi 96```

![Screenshot from 2020-07-12 18:46:51](https://user-images.githubusercontent.com/382041/87258268-44ed3900-c470-11ea-8e11-24c1e7be4a42.png)

With 192 DPI, GTK elements don't scale properly since Lazarus still uses GTK2, which doesn't have support for DPI scaling.

```xrandr --output DP-2 --mode 3840x2160 --dpi 192```

![Screenshot from 2020-07-12 18:47:12](https://user-images.githubusercontent.com/382041/87258269-4585cf80-c470-11ea-9f6a-be36e23243a1.png)

**Possible solution:**
Consider using QT5 which has proper DPI scaling support: https://wiki.lazarus.freepascal.org/Qt5_Interface#Lazarus

**Comment by benjamimgois** [comment]
Hey @MetaDark , GTK2 really have some issues with HiDPI scalling. I already tried a build with QT5 but last time i got some transparency problems. I'm looking forward to migrate Goverlay to QT5 as well, just waiting for a better lazarus-qt5 base.

**Comment by stephanlachnit** [comment]
Quote from the Wiki:

> Some distributions us Wayland by default (eg the default Fedora with a GNOME desktop) and QT5 does not work with Wayland.

That would be a real bummer - I don't know if this is up-to-date, but no Wayland support would make this not work out-of-the-box on some major distros, e. g. Debian, Ubuntu, Fedora.

**Comment by akien-mga** [comment]
> I don't know if this is up-to-date, but no Wayland support would make this not work out-of-the-box on some major distros, e. g. Debian, Ubuntu, Fedora.

I think that might be outdated. Qt5 does seem to have Wayland support via a dedicated plugin: https://wayland.freedesktop.org/qt5.html
It's packaged as `qtwayland5` in my distro Mageia. I'm not sure if all distros install it by default as part of their Qt or Wayland packaging though, but that's something which will likely happen little by little as it becomes a need.

**Comment by benjamimgois** [comment]
Fixed in 0.4.1 with the migration to QT5
