### ISSUE TITLE
Missing libMangoHud.so, overlay not working

### ISSUE THREAD

**Issue by JohnTrevis** [benjamimgois/goverlay#48]
In the gui, it states that libMangoHud.so is missing. I have globally enabled the overlay and it doesn't seem to appear in any games. The file is definitely there, it is located under /usr/lib/libMangoHud.so.

**Comment by stephanlachnit** [comment]
See https://github.com/benjamimgois/goverlay/issues/21.

**Comment by benjamimgois** [comment]
The missing LibMangohud.so message is fixed in the latest git, should be in the next official release.

**Comment by benjamimgois** [comment]
Fixed in 0.3.7
