### ISSUE TITLE
Theme issues on KDE Plasma with breeze-gtk

### ISSUE THREAD

**Issue by akien-mga** [benjamimgois/goverlay#51]
I'm running KDE Plasma with the default Breeze (not Breeze Dark) theme, and the GTK 2 and 3 themes configured to use breeze-gtk too:
![Screenshot_20200726_134046](https://user-images.githubusercontent.com/4701338/88478081-b5528a80-cf45-11ea-9728-487f4d0d31aa.png)

Here's how goverlay 0.3.6 then looks like:
![Screenshot_20200726_134158](https://user-images.githubusercontent.com/4701338/88478091-c8fdf100-cf45-11ea-8b22-5f70eb0d2708.png)

The text in the About dialog is unreadable.

It would likely be good if there was support for a light theme matching the desktop defaults, but I don't mind a dark theme specific to goverlay as long as it's consistent.

**Comment by stephanlachnit** [comment]
You can try to build it with the Qt backend, see https://github.com/benjamimgois/goverlay/issues/44.

**Comment by benjamimgois** [comment]
@akien-mga the lack of consistence in the about dialog is my mistake. I had to ajust the font colors to match the rest of the program... Will fix that in 0.3.7. Thanks for the report !

**Comment by benjamimgois** [comment]
Fixed in 0.3.7
