### ISSUE TITLE
Goverlay doesn't work

### ISSUE THREAD

**Issue by Toadfield** [benjamimgois/goverlay#52]
It doesn't work,when I save the settings for VkBasalt and MangoHud and then go into the launch options for steam games and do "MANGOHUD=1".
The setting "Global Enable" for VkBasalt and MangoHud doesn't work.
When I test the configuration I made inside Goverlay for VkBasalt or MangoHud everything works,but not in games.
"I use Manjaro"

**Comment by benjamimgois** [comment]
@Toadfield when you activate the Global Enable you don't need to use the "MANGOHUD=1" option inside steam. If the configs work in VKcube and glxgears (tests inside goverlay) it should work on games too. Are you using the Steam flatpak version ?

**Comment by Toadfield** [comment]
I don't use the steam flatpak version,does it only work in the flatpack version? (I use the "steam-manjaro" Package).
I tried it with a non steam game too,but it didn't work,so does "global enable" only activates it for every steam and Lutris games,or do I miss something?
And when "global enable" only works for steam and Lutris games,how can I use it for non steam games?

**Comment by benjamimgois** [comment]
Actually the flatpack version is the problematic one, the steam-manjaro package is the correct and should be working. The global enable works for any vulkan application that you run on your PC. Note that after activate the global enable you have to reboot your PC. How do you install Goverlay ? are you using the binary package from github ? or do you install it from the AUR on pamac ? On manjaro and arch-based distro it's better to use the AUR version (or get it from the chaotic-aur)

**Comment by Toadfield** [comment]
I installed "GOverlay-git" with Pamac and reboot my pc.
I didn't test it with a vulkan game,I tested it with cs:go and gmod,I think that cs:go uses opengl and for gmod,I don't know which api it uses,but shouldn't it work with opengl and dxvk games too?

**Comment by benjamimgois** [comment]
So i think that's the problem... actually there's some problems hooking mangohud with some opengl games. Try to add `MANGOHUD_DLSYM=1` to the steam options (or lutris config). If the game is a 32bit game, you can also try to run steam with `mangohud.x86 steam`. This information is on the mangohud main github page, if you still have problems you should ask for help on Mangohud channels. Hope it helps...

> Normal usage
> To enable the MangoHud overlay layer for 64bit Vulkan and OpenGL, run :
> 
> mangohud /path/to/app
> 
> Or
> 
> mangohud.x86 /path/to/app for 32bit OpenGL
> 
> For Lutris games, go to the System options in Lutris (make sure that advanced options are enabled) and add this to the Command prefix setting:
> 
> mangohud
> 
> For Steam games, you can add this as a launch option:
> 
> mangohud %command%
> 
> Or alternatively, add MANGOHUD=1 to your shell profile (Vulkan only).
> 
> OpenGL
> OpenGL games may also need dlsym hooking. Add MANGOHUD_DLSYM=1 to your command like MANGOHUD_DLSYM=1 mangohud %command% for Steam.
> 
> Some Linux native OpenGL games overrides LD_PRELOAD and stops MangoHud from working. You can sometimes fix this by editing LD_PRELOAD in the start script LD_PRELOAD=/path/to/mangohud/lib/

**Comment by Toadfield** [comment]
I tried it with Dota 2 and enabled Vulkan,and it didn't work.
I didn't test the things you mentioned to make it work with opengl.
