### ISSUE TITLE
Doesn't save in gaming mode (Steam Deck)

### ISSUE THREAD

**Issue by ASmyrnyi** [benjamimgois/goverlay#54]
After I configured goverlay to open in gaming mode, I tried to make some changes to one of the performance overlays there, but after pressing Save the goverlay app just freezes for two minutes and says "Config Saved", however there are no changes being applied. In desktop mode all works as intended.

**Comment by benjamimgois** [comment]
@ASmyrnyi Goverlay will not work for the gaming mode. Steamdeck uses the MangoAPP (a diferent version o mangohud integrates into gamescope). I don't know why the interface is freezing, but even if it doesn't it wouldn't work anyway.

**Comment by ASmyrnyi** [comment]
@benjamimgois sorry, wasn't aware of this. Do you by any chance know if it's possible to edit MangoApp configs?

**Comment by benjamimgois** [comment]
No problem @ASmyrnyi , i also don't have much info about mangoApp. I think the best place to ask is at Mangohud discord.
