### ISSUE TITLE
Mangohud overwriting application's vsync setting (Vulkan)

### ISSUE THREAD

**Issue by warriormaster12** [benjamimgois/goverlay#55]
For context, I posted this issue at first on mangohud's github page. After explaining the issue to devs, they suggested to report this issue here since it seems to be an issue with Goverlay front-end and not mangohud itself.

Here's the original issue post:https://github.com/flightlessmango/MangoHud/issues/309

**Comment by benjamimgois** [comment]
I'll take a look as soon as possible. Hold on

**Comment by warriormaster12** [comment]
@benjamimgois no problem

**Comment by benjamimgois** [comment]
@warriormaster12 i'm checking your issue before releasing version 0.3.8. For what i understand in the original thread, you need that your application set the vsync mode, right ? In this case you need to set goverlay to the "unset" option. Unset leaves the vsync option blank on the mangohud file. If you select the OFF option it will force the vsync=1 and override the application vsync config. Sorry took so long to answer, just now i had the time to check it deeply.

**Comment by warriormaster12** [comment]
@benjamimgois yeah, I figured that out. What confuses me is the reason for the option's existence. Do some games benefit from having this option?

**Comment by benjamimgois** [comment]
Well the "unset" option was a user request. I used to keep vsync ON is a default value in goverlay (since this is what i personaly use), but after lots of requests i change it to unset so every application can manage it self.

**Comment by warriormaster12** [comment]
Ah right, I guess it wasn't clear to me what was the purpose of the option but thanks for clarifying :D
