### ISSUE TITLE
Mangohud on Goverlay is not showing me temps

### ISSUE THREAD

**Issue by skul420** [benjamimgois/goverlay#57]
Hello,

I was recently messing around with Goverlay, I changed the theme of the HUD from simple white to Old Afterburner because I was curious but now I can't see CPU/GPU temperatures on my mangohud. I can use the graphs & histograms but the numbers don't show up on the HUD. Tried installing & reinstalling off the AUR, using goverlay-git right now but it defaults back to VRAM, RAM, FPS, frame count, or most recently it's back to before I uninstalled. What should I do?

**Comment by benjamimgois** [comment]
Just remove goverlay and mangohud folders.

/home/benjamim/.config/goverlay/
/home/benjamim/.config/MangoHud/

Then restart goverlay and it should be at stock settings.

**Comment by skul420** [comment]
So I did just that. It still won't show my temps, and even worse it doesn't show my frequencies either. Just RAM/VRAM

Update: the HUD is scrunching everything together. The graphs, the VRAM & RAM, everything. I don't have a clue on why it does this when I add to the settings.

**Comment by benjamimgois** [comment]
That's a strange behavior. After saving the config in goverlay, copy and mangohud.conf file inside `$HOME/.config/MangoHud/ `and paste it here.

**Comment by skul420** [comment]
I went on reddit & figured out the issue, apparently my mangohud.conf file had a bunch of unneccessary values & did not have gpu/cpu_temps logged in the file. Pretty weird, but I got it solved. Thanks for the help.
