### ISSUE TITLE
Bottom Left shows mangohud is missing even though it's installed

### ISSUE THREAD

**Issue by LesleyGrossman** [benjamimgois/goverlay#57]
Hey there, 

in goverlay the bottom left corner shows mangohud is missing even though I installed it, if not over the AUR or building it manually. 
Why does it do that? Am I missing anything?

**Comment by benjamimgois** [comment]
Hi @LesleyGrossman , have you installed Mangohud with it install script ? If yes, i suggest you to uninstall via the script and use only the AUR version. About the Globally enablement of Mangohud, check your **.profile** file inside your home directory if there's a line `"export MANGOHUD=1"`

**Comment by LesleyGrossman** [comment]
I uninstalled it with that script and installed the AUR version but it still showed up like that. I uninstalled goverlay and the .profile is showing up correct. I will try to reinstall it to see if that pops up again.

**Comment by LesleyGrossman** [comment]
I have reinstalled Goverlay and mangohud global enable option still doesn't work in Steam (even after restarting the system). I still have to add it manually into the launch options.

**Comment by leucome** [comment]
I have the same issue.  Goverlay report a Missing Mangohud even thought it is installed and working as expected. 
I also installed some git version of Mangohud  with install script in the past.  I may investigate this.

**Comment by benjamimgois** [comment]
@leucome this issue is due to a filename change in recent mangohud 0.5.1, it's already fixed in the latest 0.3.8 that i must release this week.

**Comment by benjamimgois** [comment]
Fixed in 0.3.8
