### ISSUE TITLE
Cannot extract tar with the instructions in README

### ISSUE THREAD

**Issue by luni3359** [benjamimgois/goverlay#59]
It's not possible to follow the command listed in the tarball section (``tar -zxvf goverlay*.tar.gz``), first because the file names in the releases have changed from ``.tar.gz`` to ``tar.xz`` since version 0.3.4, but even changing the command to ``tar -zxvf goverlay*.tar.xz`` doesn't work, here's the error:
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
Important to note that the file does extract properly when I use the desktop environment's Extract menu entry.

**Comment by benjamimgois** [comment]
I completely forgot to update the instructions. The correct command is `tar -xf ` now... already fixed, Thanks for reporting.
