### ISSUE TITLE
Open existing mangohud.conf into options

### ISSUE THREAD

**Issue by arrowgent** [benjamimgois/goverlay#6]
each time you open goverlay it returns to "default settings"

it should read the existing .conf and set those options on the ui

**Comment by benjamimgois** [comment]
I'll try to work on that in the future, but it's not a big priority right now.

**Comment by ademlabs** [comment]
I think it should read the existing settings as well, it would make this GUI way more friendlier to use.

**Comment by LiamDawe** [comment]
Consider this another request for loading existing settings, it's the expected behaviour of such a thing.

**Comment by benjamimgois** [comment]
Initial implementation in 0.3.7
