### ISSUE TITLE
nvidia no stat

### ISSUE THREAD

**Issue by Airmancooma** [benjamimgois/goverlay#60]
there are two gpum one amd and one nvidia i can see the stat of the amd one, so its clock speed memory clock speed utilization. However, nvidia has only 0 0 for clock and gb, not for vram. What could be the problem with ubuntu based distro

![image](https://github.com/benjamimgois/goverlay/assets/107194958/2ae54e1a-014d-420f-bf0b-e016f07c449e)

**Comment by benjamimgois** [comment]
@Airmancooma  please, post your mangohud.conf file and the `lspci` output

**Comment by Airmancooma** [comment]
@benjamimgois 

################### File Generated by GOverlay ###################

toggle_fps_limit=F1


legacy_layout=false
pci_dev=0:01:00.0
gpu_stats
gpu_temp
gpu_core_clock
gpu_mem_clock
gpu_load_change
gpu_load_value=50,90
gpu_load_color=FFFFFF,FFAA7F,CC0000
gpu_text=GPU
cpu_stats
cpu_temp
cpu_mhz
cpu_load_change
core_load_change
cpu_load_value=50,90
cpu_load_color=FFFFFF,FFAA7F,CC0000
cpu_color=2e97cb
cpu_text=CPU
io_color=a491d3
vram
vram_color=ad64c1
ram
ram_color=c26693
fps
engine_color=eb5b5b
gpu_color=2e9762
vulkan_driver
wine_color=eb5b5b
frame_timing=1
frametime_color=00ff00
media_player_color=ffffff
table_columns=3
background_alpha=0.4
font_size=24

background_color=020202
position=top-left
text_color=ffffff
round_corners=0
#GOVERLAY_THEME=mangohuddefault
toggle_hud=F1
toggle_logging=Shift_L+F2
upload_log=F5
output_folder=/home/airmancooma
media_player_name=spotify


![Screenshot from 2023-05-17 11-36-08](https://github.com/benjamimgois/goverlay/assets/107194958/97d72dbf-d6e1-4c25-a5e1-b80798687fee)
![Screenshot from 2023-05-17 11-36-34](https://github.com/benjamimgois/goverlay/assets/107194958/2f356aa8-9e29-4dea-b5a6-7bd8f1d44b39)

**Comment by Airmancooma** [comment]
> @Airmancooma please, post your mangohud.conf file and the `lspci` output

Are you here?

**Comment by benjamimgois** [comment]
> > @Airmancooma please, post your mangohud.conf file and the `lspci` output
> 
> Are you here?

Sorry @Airmancooma , forgot to answer. I take a look in your lscpi to see if there's any new referente to a vga controller since goverlay make a filter based on "VGA Compatible controller" string. It doesn't seem to be the issue. Another question, do you installed the nvidia proprietary driver ? If you are running the opensource "nouveau"it might explain why you have no output.

**Comment by Airmancooma** [comment]
> 

Yes the driver is downloaded correctly and the nouveau driver is disabled. I'm doing my own operating system and I don't understand why it doesn't print out, maybe there's something not installed that I should have installed besides the driver?

**Comment by benjamimgois** [comment]
check if you have the vulkan-icd-loader

**Comment by Airmancooma** [comment]
> check if you have the vulkan-icd-loader

 dpkg -l | grep vulkan
ii  libvulkan1:amd64                          1.3.239.0-1                            amd64        Vulkan loader library
ii  libvulkan1:i386                           1.3.239.0-1                            i386         Vulkan loader library
ii  mesa-vulkan-drivers:amd64                 23.1.2~kisak1~k                        amd64        Mesa Vulkan graphics drivers
ii  vulkan-tools                              1.3.239.0+dfsg1-1                      amd64        Miscellaneous Vulkan utilities
airmancooma@airmancooma:~$ 
and btw i use wayland

**Comment by benjamimgois** [comment]
ouch... sorry man. I really dont know what else it can be. Maybe the Mangohud discord could help you more.

**Comment by Airmancooma** [comment]
> ouch... sorry man. I really dont know what else it can be. Maybe the Mangohud discord could help you more.

Okay, thanks for the help anyway!
