### ISSUE TITLE
Enabling vkBasalt causes instant crashes - wrong path to textures and shaders

### ISSUE THREAD

**Issue by JacekJagosz** [benjamimgois/goverlay#62]
I'm maintainer for GOverlay on Solus.
Using newest GOverlay (0.3.8) and vkBasalt (0.3.2.2).
When I enable vkBasalt and enable SMAA any vulkan immediately crashes with: 
`vkBasalt err:   couldn't open texture: /home/jacek/.local/share/reshade/AreaTex.dds`
So it was searching for file at `/home/jacek/.local/share/reshade/AreaTex.dds`, but it really was at `/home/jacek/.local/share/reshade/Textures/AreaTex.dds` so when I copied all files from `Textures` to main `reshade` folder, it stopped crashing.

Then if I enable CAS it crashes with:
 ```
vkBasalt err:   failed to load shader file: 
vkBasalt err:   Does the filepath exist and does it not include spaces?
```
So clearly the paths to shaders and textures are configured incorrectly. Do you know if that's an issue with my packaging or GOverlay?

**Comment by benjamimgois** [comment]
Hey @JacekJagosz , i just checked the SMAA and CAS. They both seems to works fine here, there's some effects on reshade the doesn't work (don't know if it's a problem with vkbasalt or just a incompatibility with linux). Try to erase the `/home/benjamim/.config/vkBasalt/vkBasalt.conf `and create a new one with goverlay. It should look similar to this one https://justpaste.it/2f18e

**Comment by JacekJagosz** [comment]
Deleted the `vkBasalt.conf`, configured it with GOverlay, the config file is exactly the same to yours (minus the account name).
Still when I try to run Vulkan app I get `vkBasalt err:   couldn't open texture: /home/jacek/.local/share/reshade/AreaTex.dds` and the texture it is looking for is at `/home/jacek/.local/share/reshade/Textures/AreaTex.dds`.
To make it work it only needs a change in the first line of `vkBasalt.conf` from:
`reshadeTexturePath = /home/jacek/.local/share/reshade`
to
`reshadeTexturePath = /home/jacek/.local/share/reshade/Textures`

**Comment by JacekJagosz** [comment]
[Here](https://dev.getsol.us/T9299) is the forum where with other user we tested different things. Here are our conclusions:

1. CAS only works if there is other effect enable (otherwise causes crash)
2. Some effect just work (like MXAO), while other require you to add "/Textures" to `reshadeTexturePath` (like SMAA). Adding this doesn't brake anything
3. Syncing from the GOverlay didn't download all the shaders that are listed in GOverlay, so he had to download it from [here](https://github.com/crosire/reshade-shaders/archive/master.zip) and manually copy them there. This wasn't a problem for me.

After changing all that it works for us.

**Comment by benjamimgois** [comment]
@JacekJagosz i just discover what is happening... in goverlay code i was cloning the [reshade-shaders](https://github.com/crosire/reshade-shaders.git) directly. But there was a change in the repository recently and broke my implementation. I should've forked the repo and clone it from there. Sorry for tooking so long, i'll release a fix update for it.

**Comment by JacekJagosz** [comment]
Not a problem, it is awesome you have created such a great utility and are actively improving. I will update it in Solus repos as soon as possible.

**Comment by benjamimgois** [comment]
@JacekJagosz i just made a test build fixing the problem. Please, check if it works for you... 
[goverlay038f.zip](https://github.com/benjamimgois/goverlay/files/5313687/goverlay038f.zip)

Actually SMAA effect from reshade seems broken to me, i still need to create a curated list of effects that works fine on vkBasalt/Linux.

**Comment by JacekJagosz** [comment]
Unfortunately that didn't fix anything :/ If you want to make SMAA and many other effects work, just add `Textures` to the end of `reshadeTexturePath = /home/jacek/.local/share/reshade/` in `~/.config/vkBasalt/vkBasalt.conf`.
Then the line should look like `reshadeTexturePath = /home/jacek/.local/share/reshade/Textures`.
I even posted a pull request which fixes this incompatibility for me. 
Then only bug left is why it crashes when CAS is the only enabled effect.

**Comment by benjamimgois** [comment]
Did you erase the reshade folder and clone it again ? Now the textures folder and shaders folder shoud look like this

![reshade folders](https://user-images.githubusercontent.com/7688496/94844006-f2c70e80-03f3-11eb-99ac-b2a506430a82.png)

**Comment by JacekJagosz** [comment]
I did delete it and those folders look exactly like on your screen, but they looked that way even with 0.3.8. I don't know what this new one is supposed to fix, because all the things that didn't work still don't work, like SMAA or CAS without other effects enabled.
What should be different with this test build?

**Comment by benjamimgois** [comment]
The original build you get the reshade files from https://github.com/crosire/reshade-shaders.git. But, as pointed, this repo were modified and now has just a couple of files in Shaders and Textures folders. The "0.3.8F" build takes get the reshade files from https://github.com/benjamimgois/reshade-shaders , where i restored all the original missing files.

**Comment by JacekJagosz** [comment]
Now I get it, sorry for all the trouble.
Thank you for your amazing work!

**Comment by benjamimgois** [comment]
Ops, i didn't mean to close the issue. Just pushed the changes to git. Please, check if it works now.

**Comment by JacekJagosz** [comment]
Tested newest git commit, now both issues are fixed. Thank you so much!
Are you going to create a new release then, so I can easily update it for Solus?

**Comment by benjamimgois** [comment]
Thanks for reporting and helping with the fix @JacekJagosz  ! i'll release it officially in the next 0.3.9 version.
