### ISSUE TITLE
How can I import a already existing MangoHud.conf in goverlay?

### ISSUE THREAD

**Issue by 0nvx52lt** [benjamimgois/goverlay#65]
I already tried copying the MangoHud.conf-file in the path where goverlay searches for it but it still doesn't accept my custom MangoHud.conf-file. Changing the file via goverlay everytime can be annoying if you want to reinstall your OS often. Is there really no way to just import the .conf-file in goverlay?

The .conf-file can be found below:
[https://files.catbox.moe/i4odjx.conf](url)

**Comment by benjamimgois** [comment]
Right now it's not possible. I'm implementing a new way goverlay deals with configuration variables that will enable this in the future.

**Comment by 0nvx52lt** [comment]
Awesome, thank you very much! It's great to see developers who actually answer and talk with their community! I appreciate it!
