### ISSUE TITLE
nothing changes

### ISSUE THREAD

**Issue by itayalush1** [benjamimgois/goverlay#67]
ok so i really want to configure mangohud, but when i toggle or change anything, even after rebooting the system, nothing actually changes and i have no idea why, please help :)

**Comment by benjamimgois** [comment]
@itayalush1 what distro and desktop are you using ? I ask because recently i got a similar problem with Manjaro KDE, but it works fine on Gnome and Cinnamon.

**Comment by itayalush1** [comment]
im on arch, i3wm

**Comment by benjamimgois** [comment]
Goverlay modify the `.profile` file in your home folder, the problem i had on Manjaro KDE is that it also creates the file `.bash_profile` on the home folder. According to [this](https://nanxiao.me/en/why-doesnt-profile-take-effect-in-arch-linux/) article, when the bash_profile exists the system doesn't check the .profile. If that's your case, i suggest try to rename the `.bash_profile` to `.bash_profile.bak` and restart your system.

**Comment by itayalush1** [comment]
where do i find this .bash_profile file?

**Comment by benjamimgois** [comment]
inside your home folder.

**Comment by benjamimgois** [comment]
@itayalush1 does it work ?
