### ISSUE TITLE
Unlock custom framerate limit.

### ISSUE THREAD

**Issue by MekaDragon** [benjamimgois/goverlay#7]
Hi!

This tool is awesome, but why not let us set a custom framerate limit?

For example, 144 is my monitor Hz, but Freesync acts weird and it deactivates often if it's limited to 144, so it's better to limit it to 140 or so.

It's easy to do in the .conf file, but it would make this tool even more comfier.

Thanks.

**Comment by benjamimgois** [comment]
Sure @MekaDragon , i'll add this feature today. I haven't considered freesync issues.

**Comment by benjamimgois** [comment]
Implemented in 0.2.1 beta.

**Comment by jarrard** [comment]
For me this is stuck on 1 and greyed out even when selecting custom option. Maybe a bug?
Had to adjust it directly in the conf.
