### ISSUE TITLE
Junction and memory tempo

### ISSUE THREAD

**Issue by rioxrenato** [benjamimgois/goverlay#70]
Hi, I'd like to report that, when marking the options to show junction temp and memory temp, it does not load the temps after clicking save, and on closing and returning to the software the options get unchecked...

the graphics card I use have those sensors, it's a 5700xt, anyway I can help just let me know

**Comment by benjamimgois** [comment]
Hi @rioxrenato , the git version is a work in progress. The function is not yet implemented

**Comment by benjamimgois** [comment]
Fixed in latest 1.2 release
