### ISSUE TITLE
goverlay doesn't show temperatures

### ISSUE THREAD

**Issue by SonGoku90** [benjamimgois/goverlay#71]
![2023-08-23_21-27](https://github.com/benjamimgois/goverlay/assets/57522176/dfc77f5f-28c4-4c03-a635-220992a0779b)
I have Endeavor installed in my pc and when I install goverlay it doesn't show cpu and gpu temperatures. How to solve it?

**Comment by benjamimgois** [comment]
Try also enabling `Average load` on GPU and CPU

**Comment by SonGoku90** [comment]
Thanks a lot this works.
