### ISSUE TITLE
"Access violation" when opening GOverlay (OpenSUSE + KDE + Wayland)

### ISSUE THREAD

**Issue by GrgMdmn** [benjamimgois/goverlay#74]
Hello. I am embarrased because GOverlay does not work anymore on my OpenSUSE installation. It worked these previous days, but now, it does not. Here is the message I have when I try to open GOverlay : 
![image](https://github.com/benjamimgois/goverlay/assets/68954220/7b7a06b1-4c1c-4d0e-8371-de6febded53a)

When launching it from a terminal : 
```
goverlay
[FORMS.PP] ExceptionOccurred 
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $00007F7E45AF564B
```

The mangohud and goverlay versions installed are respectively and 0.7.0-1.1 and  0.9.1-1.4, installed from the SUSE repo, using Discover. I have tried re-installing them using zypper, using opi, and each time, it is impossible to make goverlay work. For your information, the previously configured mangohud overlay is still active in games, so I think the problem really comes from GOverlay.

Do you have any idea on how to solve this problem ?

**Comment by benjamimgois** [comment]
@GrgMdmn , your problem might be related to wayland. The original Goverlay script forces it to run in x11 mode. Try to run it from the terminal with:

```
export QT_QPA_PLATFORM=xcb
mangohud --dlsym /usr/lib/goverlay
```

The latest git version is already wayland compatible, but it is in early alpha

**Comment by GrgMdmn** [comment]
Thank you very much ! The environment variable works well, I have added it to my GOverlay app (sorry, interface is in French) : 
![image](https://github.com/benjamimgois/goverlay/assets/68954220/66827fa7-7668-4e63-861d-6f02d3c33357)

Now everything is working fine ! :)

**Comment by AeliusSaionji** [comment]
This has reared its head again with he latest release - pascube seems to be the offending party.
