### ISSUE TITLE
goverlay-bin no longer in AUR

### ISSUE THREAD

**Issue by Termuellinator** [benjamimgois/goverlay#79]
I'm not sure what happened or why `goverlay-bin` was removed from AUR. The last PKGBUILD i have of that still works, so i could reinstate it if desired and the removal wasn't initiated by you.
If the removal was intentional, the README.md should no longer mention it ;)

**Comment by benjamimgois** [comment]
Since Goverlay was added to Arch repositories there's no need for the -bin version in the AUR. I'll update the README. Thanks for the tip

**Comment by Termuellinator** [comment]
Oh, nice - didn't notice that. :D 
That's even better of course :+1:

**Comment by Termuellinator** [comment]
I just noticed - while you removed the mention of the AUR package i'd mention that fact that it is in the official repos now, too :)
