### ISSUE TITLE
coisas que não estão funcionando

### ISSUE THREAD

**Issue by rodrigobbarros** [benjamimgois/goverlay#8]
o global enable não esta funcionando, o core frenquency da gpu não aparece minha gpu é uma nvidia gtx 1050ti, disco IO também não esta aparecendo, o crosshair não apresenta nenhuma mudança, e as configurações toda vez que abre o goverlay elas ficam tudo zerada tendo que fazer de novo. 
uma dica se você pode-se colocar a frequência da cpu sem ter que mostrar todos os núcleos do processador seria legal.
muito bom o seu projeto

**Comment by benjamimgois** [comment]
Rodrigo, o core frequency e disk IO só foram adicionados apartir da versao 0.3 do Mangohud. verifique qual versao voce tem instalado. Qual distribuição voce está usando ? Está na ultima versão do goverlay ?

**Comment by rodrigobbarros** [comment]
sim estou usando a 0.3.1 do mangohud, uso ubuntu 19.10, estou usando a ultima versão do goverlay.
eu sou o rapaz que fez o vídeo no youtube do goverlay.

**Comment by rodrigobbarros** [comment]
tudo bom benjamimgois instalei o mangohud e o goverlay no ubuntu 20.04 beta e esta tudo funcionando apenas as configurações que quando abre o goverlay ela fica toda zerada

**Comment by benjamimgois** [comment]
nossa, ja estava preocupado... todos os testes que eu fiz estavam funcionando bem. Realmente por enquanto o funcionamento é este mesmo,ele sempre carrega a configuração zerada, no futuro pretendo ler a configuração o usuário e exibir no painel. Mas ainda não tem previsão de implementação.

Obrigado pelo feedback.
