### ISSUE TITLE
I have a GLIBC_2.34 not found error when I hit ./start_goverlay.sh

### ISSUE THREAD

**Issue by CSahajdacny** [benjamimgois/goverlay#8]
`./goverlay: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.34 not found (required by ./goverlay)`

**Comment by benjamimgois** [comment]
take a look at #4

**Comment by Corben78** [comment]
I have the same issue, I've built mangohud from source, but I still get the GLIBC_2.34 not found error.
I'm on Ubuntu 20.04.
