### ISSUE TITLE
Goverlay require ReplaySorcery ?

### ISSUE THREAD

**Issue by Augusto7743** [benjamimgois/goverlay#81]
Thanks for reading my topic.
In Goverlay GUI has the message about not installed ReplaySorcery.
Only are installed MangoHud and vkbasalt.
Goverlay require ReplaySorcery for MangoHud and vkbasalt work correctly ?

Have an nice day.

**Comment by benjamimgois** [comment]
Hi @Augusto7743 , ReplaySorcery was considered a dependency because it was the third module implemented in goverlay, it isn't required. I said "was" because replaysorcery was dropped in the last development version.

**Comment by benjamimgois** [comment]
Replaysorcery removed in 1.0 release
