### ISSUE TITLE
[Feature Request] A Reshade like menu that I can use in game to change mangohud and vkbasalt settings while the game is running

### ISSUE THREAD

**Issue by Toadfield** [benjamimgois/goverlay#81]
I would like to be able to open an menu [like that](https://i.imgur.com/TwPtk8a.png) in game and then do thing like change how mangohud looks and change cas sharpening for vkbasalt or add or remove reshade shaders.
Btw is it even possible to change settings while in game for standalone mangohud and vkbasalt?

**Comment by stephanlachnit** [comment]
This is way beyond the possible capabilities of GOverlay. This requires MangoHud and vkBasalt to check the config file for changes (which also would be a performance impact).

**Comment by Toadfield** [comment]
I asked on the Mangohud Github page and [someone answered me](https://github.com/flightlessmango/MangoHud/issues/399) that most things are possible to change while the game is running.
I didn't tested it though,but I will do that later.
For vkbasalt I'm banned from posting issues there so I don't know.

**Comment by benjamimgois** [comment]
@Toadfield just like @stephanlachnit said, this is much beyond the scope of goverlay.

**Comment by Toadfield** [comment]
On Mangohud it all works and for vkbasalt I will do a feature request if they could add that I can change settings while being in game.
Cause when vkbasalt supports this,you could make that the normal GOverlay menu pops up in game by pressing a shortcut.
Cause then it will work like with reshade.
I know that could take some time to set that the GOverlay menu can be showed i game,but could you add it in the future?
