### ISSUE TITLE
Cannot run GOverlay

### ISSUE THREAD

**Issue by luni3359** [benjamimgois/goverlay#86]
Every time I try to execute it since the latest 2 releases (which I downloaded from this page) I get this error.
```
./goverlay: error while loading shared libraries: libQt5Pas.so.1: cannot open shared object file: No such file or directory
```

**Comment by yochananmarqos** [comment]
See the updated [Prerequisites](https://github.com/benjamimgois/goverlay#prerequisites), you're missing `qt5pas`. How did you install it?

**Comment by benjamimgois** [comment]
@luni3359 with the move to QT5 now you need the qt5pas package. If you are on ubuntu (or any based distro) you just need to type in a terminal:

```
sudo apt update
sudo apt install libqt5pas1 
```

**Comment by luni3359** [comment]
Sorry for the trouble guys, I had no idea we had to install that now. The program runs properly now.
