### ISSUE TITLE
Cannot launch GOverlay on Wayfire

### ISSUE THREAD

**Issue by Darklink999999** [benjamimgois/goverlay#87]
Hello, I am trying to run GOverlay on Garuda Wayfire which uses wayland and I keep getting an aexception on `FORMS.PP`. Is there something I can do about that?

**Comment by benjamimgois** [comment]
@Darklink999999 right now wayland isn't supported. But it seems there's a wayland plugin in the works for that.

https://wayland.freedesktop.org/qt5.html

**Comment by benjamimgois** [comment]
We depend on Lazarus Project and QT5 fix for it to work.

**Comment by Darklink999999** [comment]
I actually managed to get it to work by running `QT_QPA_PLATFORM=xcb goverlay` in terminal but thanks a lot for the answers! :smile:

**Comment by benjamimgois** [comment]
Loooll.... never heard of it. Searching for your solution i found that this command is forcing QT to use the X11 backend. So, it make the application run but it still doesn't work on wayland. I'll add this work around to the documentation. To get the official interface you have to force the fusion style with the command:

`QT_QPA_PLATFORM=xcb goverlay --style fusion`

![image](https://user-images.githubusercontent.com/7688496/100034224-7bea3880-2dda-11eb-9cd0-15c016e8e6d8.png)


Thanks for the help @Darklink999999
