### ISSUE TITLE
Cannot add gpu_name

### ISSUE THREAD

**Issue by cjvth** [benjamimgois/goverlay#88]
In some old version of goverlay there was and option for showing GPU name

Now there is toggle Metrics->GPU->Information->Model, but it just adds empty line to the file

**Comment by benjamimgois** [comment]
will check it for next fix release. Thanks for reporting

**Comment by benjamimgois** [comment]
@cjvth  check if it works for you in 1.1 release.

**Comment by benjamimgois** [comment]
double checked it on the new release, fixed in 1.2
