### ISSUE TITLE
Error with libQt5Pas.so.1

### ISSUE THREAD

**Issue by Aisyk** [benjamimgois/goverlay#89]
Hi,

When i try to launch goverlay 0.4.2 i have this message : 
```
./goverlay
./goverlay: error while loading shared libraries: libQt5Pas.so.1: cannot open shared object file: No such file or directory
```
OS : POS OS 20.10

**Comment by benjamimgois** [comment]
@Aisyk the new version of goverlay is based on QT5. If you take a look at the application requisites you'll see that now it needs the qt5pas package. You can install it on any Ubuntu based distro with

`sudo apt install libqt5pas1`

**Comment by Aisyk** [comment]
Thanks, theses packages aren't installed by default. ;)
