### ISSUE TITLE
Not the right home folder 

### ISSUE THREAD

**Issue by leucome** [benjamimgois/goverlay#9]
Mangohud config file is placed in 
/home/leucome/

The actual home folder is 
/mnt/home/leucome/

Goverlay do not seem to use the $HOME path but instead use /home/"username". 
I created a link between the two to make it work. I'm probably not the only one with a home folder on an other drive so it may be a good idea to take a look.

**Comment by benjamimgois** [comment]
Thanks for the suggestion @leucome , i have never consider that situation. I'll fix it on the next release.

**Comment by benjamimgois** [comment]
@leucome I just made a change on the new 0.2.4 code, see if it solves the problem for you.

**Comment by leucome** [comment]
MangoHud.conf file is still saved in 
/home/leucome/.config/MangoHud/MangoHud.conf 
instead of 
/mnt/home/leucome/.config/MangoHud/MangoHud.conf

In the saved MangoHud.conf there is a path that point to the correct home folder for the log. 
"output_file=/mnt/home/leucome/mangohud_log_" 

So there for sure a part of the code that use the defined home folder but the config saving function still point to an inexistent home folder.  

Maybe there is a broken files with the wrong path in my system, I may need to investigate this.

**Comment by leucome** [comment]
I took a look at the code. 
The procedure Tgoverlayform.saveBitBtnClick  use this path multiple time...   /home/$USER/.config/MangoHud/MangoHud.conf

I think it can be replaced by... $HOME/.config/MangoHud/MangoHud.conf

**Comment by benjamimgois** [comment]
Hey @leucome i though i had solved the issue on the last update, indeed i tried to replace every `/home/$USER` for `$HOME` but just now i realized changed just part of the code. I'll release the 0.3 version soon and i hope the fix it there.

**Comment by benjamimgois** [comment]
@leucome please check if 0.3 version solves your problem.

**Comment by leucome** [comment]
Yes, it saved the file in the expected home folder. 

There was something new occurring.  
I got a pop up warning. I can click ok and it works. 

> Access violation.
> Press OK to ignore and risk data corruption.
> Press Abort to kill the program.

In the the terminal  I get this message

> [DEBUG] Name com.canonical.AppMenu.Registrar on the session bus is owned by :1.5
> An unhandled exception occurred at $00007F60CFE5C163:
> EAccessViolation: 
>   $00007F60CFE5C163

**Comment by benjamimgois** [comment]
@leucome   Are you using the tar.gz package ? or goverlay-git from AUR ?

**Comment by leucome** [comment]
I used 
> git clone https://github.com/benjamimgois/goverlay.git
> lazbuild -B goverlay.lpi

I was not sure if the other had the latest code.

**Comment by leucome** [comment]
I just went to try the tar.gz package and it works fine.

**Comment by benjamimgois** [comment]
Yes, there was an error while uploading the 0.3 version to github, it also created a problem with the AUR packages. Now everything is fixed. Thanks for your report
