### ISSUE TITLE
GOverlay writes wrong config files.

### ISSUE THREAD

**Issue by lavadrop** [benjamimgois/goverlay#94]
According to other closed issues, GOverlay expects more than 0 effects to apply CAS.
That is incorrect, however the generated config file expects it. According to this other ticket I opened and then closed over at https://github.com/DadSchoorse/vkBasalt/issues/117
The `:` should only be used to separate effects. CAS can be used on its own, I just tried it. Just remove the `:` from `:cas`.

**Comment by benjamimgois** [comment]
@lavadrop you're correct. I was so focused on implementing all the reshade effects that i forget about the single CAS case. I'll put it on my todo list for next version. Thanks for reporting.

**Comment by benjamimgois** [comment]
Fixed in 0.4.3
