### ISSUE TITLE
Goverlay disk full on launch

### ISSUE THREAD

**Issue by november781** [benjamimgois/goverlay#94]
Fedora 39 KDE
When I try to launch Goverlay I get a disk full error despite having over 1TB on my home and root disk empty and over 500GB on any other disk connected to my system. 

Goverlay version: 0.9-5.fc39 I would build from source and test but even after installing Lazarus I seem to still be missing something, I will keep trying to see if I can get a build to replicate this issue on

Filesystems in use are:
BTRFS Root and home dir
BTRFS separate games drive
NTFS bulk drive held over from windows

to my knowledge Goverlay should not be looking for anything other than my home directory.

I do not get this error when running the app from the terminal, just when launching it from the applications menu. 

I will be happy to pull and provide any logs on request, I just am not sure about where to start looking for those.

**Comment by benjamimgois** [comment]
@november781 that's a very strange problem. Since goverlay had a huge code revamp, would you give it a try on the latest 1.0 version ? Just download the generic .tar.xz , extract and execute the file.

**Comment by november781** [comment]
1.0 at least from the tar file works fine, and it might be that some other dependency update fixed it since I'm no longer seeing this issue on 0.9-5.fc39
