### ISSUE TITLE
Vulkan Output Not Showing

### ISSUE THREAD

**Issue by Desmo5574** [benjamimgois/goverlay#98]
Anyone else not having the Vulkan output showing?
In steam games, Vulkan versions load up and work. 
However, when pressing Run, I only get the OGL output. 
I'd say that within the past 2 weeks or so Vulkan stopped showing up.

**Comment by benjamimgois** [comment]
@Desmo5574 you're probably lacking the vulkan-tools package. The "run" button execute glxgears (for opengl) and vkcube (for vulkan). Vkcube is inside the vulkan-tools package.

**Comment by Desmo5574** [comment]
Strange...vulkan-tools was installed but to be sure I purged and reinstalled. 
It still won't show up graphically when pressing RUN but when I look at my processes there is a vkcube instance running...I just can't see it. 
I can manually launch vkcube via konsole and I see it on the desktop.

**Comment by benjamimgois** [comment]
Strange indeed... What distro ? Are you using wayland ?

**Comment by Desmo5574** [comment]
KDE Neon 20.04...I'm not using wayland. 
AMD 5700XT grafx card running 20.3.1 Mesa.

**Comment by benjamimgois** [comment]
@Desmo5574 could you make a test on the latest goverlay version ? to check if it still a issue

**Comment by Desmo5574** [comment]
@benjamimgois Sorry it took awhile to get back to you...
I just downloaded the newest version of goverlay and ran "Run vkcube test". 
It works again and the gui looks fantastic! You've added a substantial amoung of things since I last played around with goverlay.

**Comment by benjamimgois** [comment]
Good to know it's working @Desmo5574 . Thanks for the kind words, Goverlay is a never ending work in progress.
