### ISSUE TITLE
Some settings do not load back correctly in 1.0

### ISSUE THREAD

**Issue by SlayerTheChikken** [benjamimgois/goverlay#99]
For example the Time checkbox and custom colors do not load back in when you relaunch Goverlay, resulting in them being reset to default once you save settings again

Extra info: package is from Aur, on EndeavourOS, KDE Plasma de, Wayland compositor

**Comment by benjamimgois** [comment]
@Slayer5934 thanks for reporting. I'll do a extra check in configs reloading

**Comment by benjamimgois** [comment]
@Slayer5934 fixed in 1.1 release
